### ISSUE TITLE
Docker image 1.65 dashboard gone and random links point to blank

### ISSUE THREAD

**Issue by ninkaninus** [librenms/docker#100]
### Behaviour

The dashboard is gone and some links redirect to blank

#### Steps to reproduce this issue

1.have a working install on latest arround 1 month old (ca version 1.64.1)
2.update to latest (version 1.65) with docker-compose up -d

################# DOCKER-COMPOSE ######################
version: "3.5"

services:
  db:
    image: mariadb:10.5
    container_name: librenms_db
    command:
      - "mysqld"
      - "--innodb-file-per-table=1"
      - "--lower-case-table-names=0"
      - "--character-set-server=utf8"
      - "--collation-server=utf8_unicode_ci"
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      - "TZ=${TZ}"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    restart: always

  memcached:
    image: memcached:alpine
    container_name: librenms_memcached
    environment:
      - "TZ=${TZ}"
    restart: always

  redis:
    image: redis:6.0-alpine
    container_name: librenms_redis
    environment:
      - "TZ=${TZ}"
    restart: always

  rrdcached:
    image: crazymax/rrdcached
    container_name: librenms_rrdcached
    volumes:
      - "./librenms/rrd:/data/db"
      - "./rrd-journal:/data/journal"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "LOG_LEVEL=LOG_INFO"
      - "WRITE_TIMEOUT=1800"
      - "WRITE_JITTER=1800"
      - "WRITE_THREADS=4"
      - "FLUSH_DEAD_DATA_INTERVAL=3600"
    restart: always

  msmtpd:
    image: crazymax/msmtpd:latest
    container_name: librenms_msmtpd
    env_file:
      - "./msmtpd.env"
    restart: always

  librenms:
    image: librenms/librenms:1.64.1
    container_name: librenms
    domainname: example.com
    hostname: librenms
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
    depends_on:
      - db
      - memcached
      - rrdcached
      - msmtpd
    volumes:
      - "./librenms:/data"
    env_file:
      - "./librenms.env"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
    restart: always

  dispatcher:
    image: librenms/librenms:1.64.1
    container_name: librenms_dispatcher
    domainname: example.com
    hostname: librenms
    depends_on:
      - librenms
      - redis
    volumes:
      - "./librenms:/data"
    env_file:
      - "./librenms.env"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
      - "REDIS_DB=0"
      - "SIDECAR_DISPATCHER=1"
    restart: always

  syslog-ng:
    image: librenms/librenms:1.64.1
    container_name: librenms_syslog
    domainname: example.com
    hostname: librenms
    depends_on:
      - librenms
    ports:
      - target: 514
        published: 514
        protocol: tcp
      - target: 514
        published: 514
        protocol: udp
    volumes:
      - "./librenms:/data"
    env_file:
      - "./librenms.env"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
      - "SIDECAR_SYSLOGNG=1"
    restart: always
##################### END #######################

#####################librenms.env##################
MEMORY_LIMIT=512M
UPLOAD_MAX_SIZE=128M
OPCACHE_MEM_SIZE=256
REAL_IP_FROM=XXX.XXX.XXX.XXX/32
REAL_IP_HEADER=X-Forwarded-For
LOG_IP_VAR=remote_addr

LIBRENMS_SNMP_COMMUNITY=librenmsdocker
MEMCACHED_HOST=memcached
MEMCACHED_PORT=11211
RRDCACHED_HOST=rrdcached
RRDCACHED_PORT=42217

LIBRENMS_SERVICE_POLLER_WORKERS=24
LIBRENMS_SERVICE_SERVICES_WORKERS=8
LIBRENMS_SERVICE_DISCOVERY_WORKERS=16

LIBRENMS_SERVICE_POLLER_FREQUENCY=120
LIBRENMS_SERVICE_SERVICES_FREQUENCY=120
LIBRENMS_SERVICE_DISCOVERY_FREQUENCY=21600
LIBRENMS_SERVICE_BILLING_FREQUENCY=300
LIBRENMS_SERVICE_BILLING_CALCULATE_FREQUENCY=60
LIBRENMS_SERVICE_POLLER_DOWN_RETRY=30
LIBRENMS_SERVICE_LOGLEVEL=INFO
LIBRENMS_SERVICE_UPDATE_FREQUENCY=300

LIBRENMS_SERVICE_PING_ENABLED=false
LIBRENMS_SERVICE_WATCHDOG_ENABLED=false

LIBRENMS_WEATHERMAP=true
LIBRENMS_WEATHERMAP_SCHEDULE=*/2 * * * *
#### Expected behaviour

> the dashboard from previous should deployment should persist and the links should work

#### Actual behaviour

> the dashboard fails to load and some random links redirect to blank 

### Configuration

* Docker version (type `docker --version`) : Docker version 19.03.12, build 48a66213fe
* Docker compose version if applicable (type `docker-compose --version`) : docker-compose version 1.24.1, build 4667896b
* Platform (Debian 9, Ubuntu 18.04, ...) : Ubuntu 20.04
* System info (type `uname -a`) : 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

### Docker info

```
> Output of command `docker info`
```
Client:
 Debug Mode: false

Server:
 Containers: 11
  Running: 11
  Paused: 0
  Stopped: 0
 Images: 23
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-40-generic
 Operating System: Ubuntu 20.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.775GiB
 Name: XXXX
 ID: GEAS:DK64:V4K2:G6CX:K3DO:T5A6:3QWF:7BTL:VLPL:U52L:SMRN:32TH
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

### Logs

```
> Container logs (set LOG_LEVEL to debug if applicable)
```
Have not done this, can do it if needed

**Comment by blakeaa827** [comment]
@ninkaninus I am seeing this as well in Chrome.  What's strange is that if I open the dashboard in Firefox, it shows up the way it did before the upgrade.  Can you see your dashboard in Firefox?

I'm not suggesting that the fix is to use Firefox.  The other pages that don't work still don't work in Firefox.  Is http://<librenms_url>/poller/log also blank for you?

**Comment by elct9620** [comment]
I have the same problem in Chrome, the dashboard didn't show and have some JavaScript error in the console. Other pages are not working correctly, too without any error.

For example, the availability status page cannot display the logo correctly even the browser shows it download correctly and I can access it by open the URL, and I cannot edit the alert, it seems some JavaScript breaks and the alert edit modal unable load the data correctly.

**Comment by nepeat** [comment]
Can confirm. Chrome and Safari are exhibiting broken behaviour as described above but LibreNMS is working in Firefox.

Other behaviour not described but is broken in chrome is
* Alerts panel is empty
* Unable to run manual Captures
```
pace.min.js:2 Uncaught DOMException: Failed to execute 'open' on 'XMLHttpRequest': Invalid URL
    at XMLHttpRequest.a.open (https://nms.local/js/pace.min.js:2:6407)
    at HTMLButtonElement.document.getElementById.onclick (https://nms.local/device/10/capture:793:21)
a.open @ pace.min.js:2
document.getElementById.onclick @ capture:793```
* All sections on Ports, Health, Wireless panes are empty

**Comment by ninkaninus** [comment]
@murrant thank you this worked.

[22:31] Ninkaninus: i tried to update my docker-compose deploy to latest, and it broke the links and the dashboard.
a rool back to 1.64.1 worked should i poste it other places?
[22:35] murrant: @Ninkaninus report an issue on the docker repo (if there isn't one already)
[22:59] Ninkaninus: @murrant  done,  just ask if you need anything, it's my first time using librenms, and the first update :)
[23:00] murrant: @Ninkaninus I think there was already some mention that base_url needed to be set in some ticket
[23:01] murrant: (now that my memory comes :D)
[23:02] Ninkaninus: Yes I read that, but it is greyed out, can it be set via .env file?
[23:02] murrant: greyed out? that means it is set in config.php, it should not be in the docker
[23:04] Ninkaninus: How do you change that when in docker?
[23:04] murrant: via the webui
[23:04] murrant: I think, maybe there is an env variable
[23:08] Ninkaninus: Ty @murrant I think I found it, it seems very promising. Have shutdown for tonight, but will try tomorrow and update the issue with my results :)

In my docker-compose.yml i added this to the librenms container:
- BASE_URL=librenms.example.com:8000/

When the container was started i was able to set the specific URL in the settings like this:
Global settings --> System --> Server --> set the specific URL
![image](https://user-images.githubusercontent.com/10107595/87118173-f1fe6080-c27a-11ea-909f-46f73ddfe2c4.png)

after i have done this it worked in chrome again, as some mentioned it was working in firefox, i did not test this, there fore i can't confirm that it is the same problem you have @nepeat @elct9620 @blakeaa827.
can one of you test this solution?

**Comment by elct9620** [comment]
It works well after setting the correct hostname and URL.

**Comment by ninkaninus** [comment]
Right now i actually had to remove the specific URL in the settings menu again after i cleared the cache.

**Comment by ninkaninus** [comment]
@elct9620 what have you changed exactly?

**Comment by elct9620** [comment]
Remove the specific URL will make it break again.

**Comment by ninkaninus** [comment]
hmm, i have removed mine, and it still works in chrome, edge and a clean install of brave.
The only change i made was the base_URL ins the docker-compose.yml file

**Comment by ninkaninus** [comment]
they actually addressed this in the change log:
https://github.com/librenms/docker/blob/master/CHANGELOG.md#165-rc1-20200703

i will close this issue as it seems to be fixed.

**Comment by crazy-max** [comment]
@ninkaninus @elct9620 @nepeat @blakeaa827 Latest image (1.65.1) should solve the `base_url` issue through the [`LIBRENMS_BASE_URL` env var](https://github.com/librenms/docker/blob/master/doc/docker/environment-variables.md#misc) (default to `/`).

**Comment by ninkaninus** [comment]
@crazy-max that should probably be documented here too:
https://github.com/librenms/docker/blob/master/examples/compose/librenms.env

if it does not falls back to the default value as /

An again thanks for the good software, keep up the amazing work.

**Comment by crazy-max** [comment]
@ninkaninus 

> that should probably be documented here too:
https://github.com/librenms/docker/blob/master/examples/compose/librenms.env

I had intended to indicate it in this configuration but I preferred to remove it because the default value is enough for most cases (and the examples too).

> An again thanks for the good software, keep up the amazing work.

You're welcome!
