### ISSUE TITLE
rrdtool version config vs installed mismatch

### ISSUE THREAD

**Issue by rigocalin** [librenms/docker#106]
In the container rootfs/etc/cont-init.d/03-config.sh the RRDTOOL is hardcoded to 1.7.0 as seen below:

`# Config : RRDcached......
\$config['rrdcached'] = "${RRDCACHED_HOST}:${RRDCACHED_PORT}";
\$config['rrdtool_version'] = '1.7.0';
EOL
fi`

But the actual version that gets installed on the container is 1.7.2.

Can we introduce an automated way to pull that?
Or worst case allow the use of variables.

**Comment by murrant** [comment]
FYI, as long as the version is >= 1.5.5.  There is no change in the operation of LibreNMS.
