### ISSUE TITLE
README.md instructions incomplete/incorrect

### ISSUE THREAD

**Issue by pcarver** [librenms/docker#11]
Following the instructions in README.md results in containers starting up, but the validate command has the wrong container name. Specifically the following command gives the following error:

```
$ docker exec -it --user librenms librenms php validate.php
Error: No such container: librenms
```
Changing the container name to `librenms_app_1` allows the validation script to run, but it reports a failure with instructions to change some permissions. If these permission changes are correct then they should be included in the instructions in README.md. The current instructions DO include `chmod 600 acme.json` but there's no mention of the rest.

```
$ docker exec -it --user librenms librenms_app_1 php validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 1.47
DB Schema | 275
PHP       | 7.2.13
MySQL     | 10.2.21-MariaDB-1:10.2.21+maria~bionic
RRDTool   | 1.7.0
SNMP      | NET-SNMP 5.7.3
====================================

[OK]    Composer Version: 1.8.0
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
[WARN]  You have not added any devices yet.
        [FIX]:
        You can add a device in the webui or with ./addhost.php
[WARN]  IPv6 is disabled on your server, you will not be able to add IPv6 devices.
[WARN]  Your install is over 24 hours out of date, last update: Sun, 30 Dec 2018 14:29:16 +0000
        [FIX]:
        Make sure your daily.sh cron is running and run ./daily.sh by hand to see if there are any errors.
[WARN]  Your local git branch is not master, this will prevent automatic updates.
        [FIX]:
        You can switch back to master with git checkout master
[FAIL]  Some folders have incorrect file permissions, this may cause issues.
        [FIX]:
        sudo chown -R librenms:librenms /opt/librenms
        sudo setfacl -d -m g::rwx /data/rrd /data/logs /opt/librenms/bootstrap/cache/ /opt/librenms/storage/
        sudo chmod -R ug=rwX /data/rrd /data/logs /opt/librenms/bootstrap/cache/ /opt/librenms/storage/
        Files:
         /data/logs/librenms.log
```

**Comment by crazy-max** [comment]
It's fixed, check the README

**Comment by pcarver** [comment]
Thanks. The validate.php command now works successfully and the output gives only warnings, no FAIL messages. However, is there additional setup required that is not documented in the README.md? Visiting http://<hostIP> results in a redirect to https://<hostIP> which results in a 404 error.

Also, on "docker-compose up -d" the following warnings are emitted which contradict the defaults listed in the README.md. Since I'm just deploying this for a "kick the tires" on a throwaway machine I figured I'd just leave the defaults. If any of the environment variables listed in the README are mandatory (i.e. can't be left unset) the README should make it clear.

```
WARNING: The TZ variable is not set. Defaulting to a blank string.
WARNING: The PUID variable is not set. Defaulting to a blank string.
WARNING: The PGID variable is not set. Defaulting to a blank string.
WARNING: The MYSQL_DATABASE variable is not set. Defaulting to a blank string.
WARNING: The MYSQL_USER variable is not set. Defaulting to a blank string.
WARNING: The MYSQL_PASSWORD variable is not set. Defaulting to a blank string.
```

Also, my SMTP server doesn't require authentication, so I set SMTP_SERVER in .env but deleted SMTP_USERNAME and SMTP_PASSWORD. When running `docker-compose up -d` it emits the following
```
WARNING: The SMTP_SERVER variable is not set. Defaulting to a blank string.
WARNING: The SMTP_USERNAME variable is not set. Defaulting to a blank string.
WARNING: The SMTP_PASSWORD variable is not set. Defaulting to a blank string.
```
So I suppose it is not reading .env. If SMTP_SERVER is required to be in libreems.env (and not just .env) it should be added to the file on GitHub. And it would be a good idea to indicate what should be done with the SMTP_USERNAME and SMTP_PASSWORD variables in the case of a non-authenticated SMTP server. (e.g. not set them at all, or set them to blank, or maybe set some other variable to squelch the warning by explicitly indicating that no username/password is required.

**Comment by pcarver** [comment]
Oh, one more thing. I don't have any PHP experience, but the PHP config on lines 132-134 looks incorrect because there's no closing angle bracket. I tried it as written and also tried adding a closing angle bracket but still get a 404 from https://hostIP/ and https://hostIP/webui.php
