### ISSUE TITLE
[Synology Nas] Devices not polled

### ISSUE THREAD

**Issue by ludipq** [librenms/docker#111]
Fresh installation on a Synology NAS in Docker.

After adding devices successfully (through GUI or CLI), they are not being polled.

![2020-08-14](https://user-images.githubusercontent.com/32069841/90286227-b3f5ed00-de75-11ea-9af7-feefa813e8b0.png)

I have the same devices added to an instance of Observium, where all of the data is polled without any problems, so there are no issues with the devices and their SNMP.

### Configuration

* Docker version (type `docker --version`) : 18.09.8
* Platform (Debian 9, Ubuntu 18.04, ...) : Synology NAS
* System info (type `uname -a`) : Linux 3.10.105 #25426 SMP Wed Jul 8 03:19:33 CST 2020 x86_64 GNU/Linux synology_avoton_rs1219+

### Docker info

```
> 
Containers: 13
 Running: 11
 Paused: 0
 Stopped: 2
Images: 14
Server Version: 18.09.8
Storage Driver: btrfs
Logging Driver: db
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs db fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 0cf16177dbb234350dc27dd2bbd1d7cebd098108
runc version: 6cc9d3f2cd512eeb3d548e2f6b75bcdebc779d4d
init version: e01de58 (expected: fec3683)
Security Options:
 apparmor
Kernel Version: 3.10.105
Operating System:  (containerized)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.786GiB
Name: 
ID: 32HH:CSXT:ZP7X:Q6FL:I556:M2ZP:K2W7:GYN6:F3F6:CXNY:N7RF:XFOV
Docker Root Dir: /volume1/@docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support

```

### Logs
Output of validate.php:

```
> bash-5.0# ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 1.66
DB Schema | 2020_06_23_00522_alter_availability_perc_column (171)
PHP       | 7.3.20
Python    | 3.8.5
MySQL     | 10.5.5-MariaDB-1:10.5.5+maria~focal
RRDTool   | 1.7.2
SNMP      | NET-SNMP 5.8
====================================

[OK]    Installed from the official Docker image; no Composer required
[OK]    Database connection successful
[FAIL]  Time between this server and the mysql database is off
 Mysql time 2020-08-14 19:49:58
 PHP time 2020-08-14 21:49:58

[OK]    Database schema correct
[WARN]  IPv6 is disabled on your server, you will not be able to add IPv6 devices.
[WARN]  Updates are managed through the official Docker image
```

**Comment by ludipq** [comment]
Okay so did some further digging, if I run `poller.php` and `discovery.php` manually in the console after adding the devices, the information is polled and the device dropdown menu becomes functional.

I think it maybe has something to do with the time zone in the php.ini being set wrong, but I can't figure out how to access it to fix the information.

**Comment by ludipq** [comment]
Managed to fix the time zone issue (the time zone in the php was correct, but not in mariadb).

Anyway, it still doesn't work. Adding a device, but it's not being polled automatically.

**Comment by crazy-max** [comment]
@ludipq Please create a proper [bug report](https://github.com/librenms/docker/issues/new?template=bug_report.md):

* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...
* Container logs

**Comment by krisha** [comment]
same issue for me, using docker integration on unraid.

1. created empty database
2. unraid pulled image from dockerhub (librenms/librenms:latest)
3. started by:
`root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='librenms' --net='br0' --ip='192.168.XXX.XXX' -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -e 'TCP_PORT_8000'='80' -e 'UDP_PORT_514'='514' -e 'MEMORY_LIMIT'='256M' -e 'UPLOAD_MAX_SIZE'='16M' -e 'OPCACHE_MEM_SIZE'='128' -e 'LISTEN_IPV6'='false' -e 'REAL_IP_FROM'='0.0.0.0/32' -e 'REAL_IP_HEADER'='X-Forwarded-For' -e 'LOG_IP_VAR'='remote_addr' -e 'DB_HOST'='192.168.XXX.XXX' -e 'DB_PORT'='3306' -e 'DB_NAME'='librenms' -e 'DB_USER'='librenms' -e 'DB_PASSWORD'='XXX' -e 'DB_TIMEOUT'='60' -e 'LIBRENMS_BASE_URL'='/' -e 'LIBRENMS_SNMP_COMMUNITY'='public' -e 'PUID'='99' -e 'PGID'='100' -v '/mnt/user/XXX/XXX/librenms/':'/data':'rw' 'librenms/librenms:latest'
d77f9c152c5e848d717bbe481662f3a30f405bbb50d299d6407e480938fbcb88
`

/mnt/user/XXX/XXX/librenms/ was empty, so a new .env was generated (just APP_KEY and NODE_ID entries inside).

There is also no poller listed inside "Settings->Poller".

**Comment by krisha** [comment]
Seems like running a second container for the dispatcher is necessary.
Used same arguments with following changes:

- different IP
- --name='librenms_dispatcher'

and additional parameters:

- -e SIDECAR_DISPATCHER=1
- -e DISPATCHER_NODE_ID=dispatcher1
- -e REDIS_HOST=localhost

Unfortunately this doesn't show up the poller (but works). To see the poller on web ui you need to setup a config.php on librenms container with e.g. following contents:
`<?php
$config['distributed_poller']                    = true;
$config['distributed_poller_name']               = php_uname('n');
$config['distributed_poller_group']              = 0;
?>`

Unfortunately then it's not possible to share the data folder between dispatcher and librenms. This would throw errors on the dispatcher container. A little bit of chaos ;)

I think it would be nice if a dispatcher and redis could be integrated into the base container. (or is there already a way to trigger that?)

**Comment by murrant** [comment]
@krisha Someone would probably want to make a different docker image to make an all in one type of docker image.

Why does the data folder need to be shared?

**Comment by crazy-max** [comment]
The minimal stack is available here: https://github.com/librenms/docker/blob/master/examples/compose/docker-compose.yml
