### ISSUE TITLE
Using Nginx instead of Traefik

### ISSUE THREAD

**Issue by mmihir82** [librenms/docker#121]
Hello, I have currently implemented using the [example/traefik/docker-compose.yml](https://github.com/librenms/docker/blob/master/examples/traefik/docker-compose.yml) 
Following issue I'm running into:
- With our current network: To Access LibreNMS GUI we have to go thru via proxy.
- I have modified the docker-compose.yml with this following: Withing Librenms service, under label:
```
      - "traefik.frontend.rule=Host:network-librenms.proxy.com"
```
Also update: /etc/hosts
```
127.0.0.1 librenms network-librenms.proxy.com
192.168.2.254 network-librenms.proxy.com librenms
```
Here is the proxy url is: ` network-librenms.proxy.com:4443`
With this above setup only way I could see reach LibreNMS GUI. But issue is with the Oxidized.  
- Oxidized failed to reach LibreNMS configure, because LibreNMS front-end is point to proxy address which is using HTTPS and fail to received certs. 
- I tried installing local LibreNMS without docker, and it was sluggish and really slow. So I went back to docker container. 
How to add in Traefik, instead of using Front-end URL, use local address so oxidized can communicate with LibreNMS.? 
I thought of switching from Traefik to Nginx, to see any changes.

**Comment by crazy-max** [comment]
Follow-up on #184

**Comment by mmihir82** [comment]
Can you provide the docket-compose example with nginx with librenms? Thanks

**Comment by rfdrake** [comment]
Here is what I'm using.  "librenms.local" needs to be changed to the full domain name of your server.  You need to place certificates in /home/user/certs with the same name.   Like "librenms.local.crt" and "librenms.local.key" for example.

    nginx-proxy:
      image: nginxproxy/nginx-proxy
      depends_on:
        - librenms
      restart: always
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - /home/user/certs:/etc/nginx/certs
      ports:
        - 80:80
        - 443:443
    librenms:
      environment:
        - "VIRTUAL_HOST=librenms.local"
        - "VIRTUAL_PORT=8000"

**Comment by mmihir82** [comment]
@rfdrake Thanks, how is the librenms will setup with nginx? can you provide the librenms with nginx
