### ISSUE TITLE
How to get autodiscovery working with librenms/docker?

### ISSUE THREAD

**Issue by sjwk** [librenms/docker#129]
Is there any documentation on the steps needed to get autodiscovery working?  I'm basically using the docker-compose 'example' as an initial test.  However it still has not discovered anything beyond the first device I added.  I gave it the correct SNMP community string via LIBRENMS_SNMP_COMMUNITY environment variable, and have added the same community string to $config['snmp']['community'] and defined $config['nets'] via a PHP file dropped into librenms/config (as per https://docs.librenms.org/Extensions/Auto-Discovery/ and https://github.com/librenms/docker/blob/master/doc/notes/edit-config.md).

It is correctly polling the core switch, and shows neighbours via both CDP and LLDP.  From looking in settings via the GUI, all the discovery and autodiscovery options look correct and enabled.  The poller settings have discovery enabled.  I can see in the logs that it runs discovery but only discovers one device (which takes it ~3 minutes - it polls in about 8s if those numbers are normal?)  No errors in the logfile.

So, what am I missing?

**Comment by bbz404** [comment]
You can try running snmp-scan.py from within the librenms container. If your config is correct it will scan the 'nets' you have defined already. If not it will show an error that it is not set. Run it with -v so you can see the IP addresses in its output.

Alternatively, you can also specify the nets for it scan if they are not added.

The devices you expect it to be able to find, are they reachable by DNS? If you want devices to be added that are not resolvable by DNS enable discovery_by_ip

**Comment by sjwk** [comment]
So, running snmp-scan.py manually did indeed pick up the devices I was expecting.  Presumably though I shouldn't need to manually do that whenever I add a device to the network?  It's been a number of years since I last ran Librenms (not via docker) and I was fairly sure it was automatic?

**Comment by crazy-max** [comment]
@sjwk Like @bbz404 said I think you should specify the networks to scan because your LAN is outside the overlay network induced by Docker.
