### ISSUE TITLE
Fail: You have a different system timezone () than the php configured timezone (PST)

### ISSUE THREAD

**Issue by Mist-Hunter** [librenms/docker#143]
### Behaviour

Fail: You have a different system timezone () than the php configured timezone (PST)

Seems to have been introduced in tag 1.69, rolling back to 1.68 resolves the issue. Maybe an alpine bug?

latest (1.69)
bash-5.0# date +"%Z %z"
 **+0000**
bash-5.0# cat /etc/timezone
America/Los_Angeles
bash-5.0# cat /etc/php7/php.ini | grep date.timezone
; http://php.net/date.timezone
date.timezone = America/Los_Angeles
bash-5.0#

1.68
bash-5.0# date +"%Z %z"
**PST -0800**
bash-5.0# cat /etc/timezone
America/Los_Angeles
bash-5.0# cat /etc/php7/php.ini | grep date.timezone
; http://php.net/date.timezone
date.timezone = America/Los_Angeles
bash-5.0#

**Comment by Mist-Hunter** [comment]
Also: Thanks for all the effort you put into these images!! I hope the bugs I've filed aren't just user error :)

**Comment by Mist-Hunter** [comment]
Maybe related? https://stackoverflow.com/questions/64473107/how-to-fix-broken-tzdata2020c-timezone-database-for-alpine

**Comment by crazy-max** [comment]
@Mist-Hunter I encounter this issue for a Go app I maintain (https://github.com/crazy-max/diun/issues/202#issuecomment-719733256 https://github.com/golang/go/issues/42216). I fixed this by using the [embedded tzdata of Go](https://golang.org/pkg/time/tzdata/) instead of the alpine package.

**Comment by murrant** [comment]
Should we be forcing the containers to run at UTC?

**Comment by crazy-max** [comment]
@murrant 

> Should we be forcing the containers to run at UTC?

It's already the [default case](https://github.com/librenms/docker/blob/master/rootfs/etc/cont-init.d/03-config.sh#L26).

**Comment by crazy-max** [comment]
@Mist-Hunter Can you try with `librenms/librenms:edge` tag and let me know?

**Comment by Mist-Hunter** [comment]
Unfortunately I'm getting the same thing with :edge

bash-5.0# date +"%Z %z"
 +0000
bash-5.0# cat /etc/timezone
America/Los_Angeles
bash-5.0# cat /etc/php7/php.ini | grep date.timezone
; http://php.net/date.timezone

**Comment by crazy-max** [comment]
Ok as @tianon said in alpinelinux/docker-alpine#117 it's a known issue:

* https://gitlab.alpinelinux.org/alpine/aports/-/issues/12057
* https://lists.alpinelinux.org/~alpine/users/%3CCAEpSaE0Qj32d-6e6mk3AG6dXouSv2MAtPR8bGJra0i15oaLj2A%40mail.gmail.com%3E

Unfortunately the [edge tzdata package](https://pkgs.alpinelinux.org/packages?name=tzdata&branch=edge) does not work too.

**Comment by crazy-max** [comment]
Ok this has been [fixed](https://gitlab.alpinelinux.org/alpine/aports/-/commit/754f23ac8f4165e21f585ac2effaa9e3e9333d01). I will rebuild the image.
