### ISSUE TITLE
docker-compose: mariadb has no matching manifest on armv7

### ISSUE THREAD

**Issue by neszt** [librenms/docker#145]
### Behaviour
The docker-compose example is producing the following error on armv7
Pulling db (mariadb:10.4)...
10.4: Pulling from library/mariadb
ERROR: no matching manifest for unknown in the manifest list entries

I know mariadb is another (official) docker, not scope of this project, but since librenms docker supports armv7, a sample file that also supports it would be good.

#### Steps to reproduce this issue

1.
```bash
git clone https://github.com/librenms/docker.git
```
2.
```bash
cd ./docker/examples/compose/
```
3.
```bash
$ uname -m
armv7l
$ docker-compose up
Pulling db (mariadb:10.4)...
10.4: Pulling from library/mariadb
ERROR: no matching manifest for unknown in the manifest list entries
```

#### Expected behaviour

```bash
$ docker-compose up
Creating network "librenms_default" with the default driver
Creating librenms_redis     ... done
Creating librenms_memcached ... done
Creating librenms_msmtpd    ... done
Creating librenms_db        ... done
Creating librenms           ... done
Creating librenms_dispatcher ... done
Creating librenms_syslogng   ... done
```

#### Actual behaviour
```bash
$ docker-compose up
Pulling db (mariadb:10.4)...
10.4: Pulling from library/mariadb
ERROR: no matching manifest for unknown in the manifest list entries
```
### Configuration

* Docker version (type `docker --version`) : Docker version 18.09.1, build 4c52b90
* Docker compose version if applicable (type `docker-compose --version`) : docker-compose version 1.21.0, build unknown
* Platform (Debian 9, Ubuntu 18.04, ...) :
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
* System info (type `uname -a`) : Linux 5.8.16-sunxi #20.08.14 SMP Tue Oct 20 22:15:32 CEST 2020 armv7l GNU/Linux
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

### Docker info
Containers: 17
 Running: 10
 Paused: 0
 Stopped: 7
Images: 21
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 1.0.0~rc6+dfsg1-3
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 5.8.16-sunxi
Operating System: Armbian 20.08.14 Buster
OSType: linux
Architecture: armv7l
CPUs: 4
Total Memory: 1.965GiB
Name: home3.dyndns.neszt.hu
ID: DYKX:HC5V:LQNP:MCB4:IXEP:U4UA:TZZV:HNM7:YCVS:AKNR:5YT5:EIMP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by crazy-max** [comment]
@neszt 

As stipulated on the [MariaDB hub readme](https://hub.docker.com/_/mariadb), there is no support for armv7. But you can try this image: https://hub.docker.com/r/linuxserver/mariadb. See also https://github.com/docker-library/official-images#architectures-other-than-amd64
