### ISSUE TITLE
docker-compose: data volume settings should be in variables

### ISSUE THREAD

**Issue by neszt** [librenms/docker#148]
Everyone likes to store their data in a different directory structure, so this should be configurable (mariadb data and librenms data). In addition, the current defaults do not clearly distinguish between data and configuration.

**Comment by crazy-max** [comment]
@neszt 

> Everyone likes to store their data in a different directory structure, so this should be configurable (mariadb data and librenms data).

Same as https://github.com/librenms/docker/issues/146#issuecomment-735564579. Feel free to bind mount in another folder if you want.

> In addition, the current defaults do not clearly distinguish between data and configuration.

Explained in https://github.com/librenms/docker/blob/master/doc/docker/volumes.md
