### ISSUE TITLE
Errors in validate in latest image

### ISSUE THREAD

**Issue by hugalafutro** [librenms/docker#152]
After pulling yesterdays image Validate spits out these errors:
```
Warning: Global lnms shortcut not installed. lnms command must be run with full path
Fix:
sudo ln -s /opt/librenms/lnms /usr/local/bin/lnms
Warning: Log rotation not enabled, could cause disk space issues
Fix:
sudo cp /opt/librenms/misc/librenms.logrotate /etc/logrotate.d/librenms
```
You can run the latter command inside the container to fix, but the first one errors out with `ln: failed to create symbolic link '/usr/local/bin/lnms': File exists` yet the validate still complains about it.

No idea as to how/if it affects the usability I just run validate after each time I recreate the container.

_note: I didn't fill rest of the form as I don't think this issue has to do with my docker version compose or system configuration etc., however I can supply the info if it's indeed needed._

**Comment by crazy-max** [comment]
@hugalafutro Cannot reproduce myself:

```
$ docker-compose exec --user librenms librenms php validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 1.70.1
DB Schema | 2020_11_02_164331_add_powerstate_enum_to_vminfo (191)
PHP       | 7.3.25
Python    | 3.8.5
MySQL     | 10.2.17-MariaDB-1:10.2.17+maria~bionic
RRDTool   | 1.7.2
SNMP      | NET-SNMP 5.8
OpenSSL   |
====================================

[OK]    Installed from the official Docker image; no Composer required
[OK]    Database connection successful
[OK]    Database schema correct
[WARN]  Log rotation not enabled, could cause disk space issues
        [FIX]:
        sudo cp /opt/librenms/misc/librenms.logrotate /etc/logrotate.d/librenms
[WARN]  Updates are managed through the official Docker image
```

Also that's just warnings but the `Global lnms shortcut not installed` one is strange.

**Comment by hugalafutro** [comment]
Note the error doesn't come up if you run validate from cli, ie on my end:
```
sammael@nms:~/docker/librenms$ docker-compose exec --user librenms librenms php validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 1.70.1
DB Schema | 2020_11_02_164331_add_powerstate_enum_to_vminfo (191)
PHP       | 7.3.25
Python    | 3.8.5
MySQL     | 10.4.17-MariaDB-1:10.4.17+maria~focal
RRDTool   | 1.7.2
SNMP      | NET-SNMP 5.8
OpenSSL   |
====================================

[OK]    Installed from the official Docker image; no Composer required
[OK]    Database connection successful
[OK]    Database schema correct
[WARN]  IPv6 is disabled on your server, you will not be able to add IPv6 devices.
[WARN]  Updates are managed through the official Docker image
```
all looks good, but running validate in web ui yields the 
```
Warning: Global lnms shortcut not installed. lnms command must be run with full path
Fix:
sudo ln -s /opt/librenms/lnms /usr/local/bin/lnms
```

**Comment by hugalafutro** [comment]
inside the container 
```
bash-5.0# ls -la /usr/local/bin/lnms 
-rwxr-xr-x 1 root root 68 Dec 10 01:54 /usr/local/bin/lnms
```
perhaps it needs to be a link as the fix in validate suggest not physically be there I dunno

**Comment by murrant** [comment]
/usr/local/bin is not in PATH for the librenms user apparently...

**Comment by crazy-max** [comment]
@murrant 

> `sudo ln -s /opt/librenms/lnms /usr/local/bin/lnms`

We should skip this check for our Docker image because we have our pre-built shortcut: https://github.com/librenms/docker/blob/master/rootfs/usr/local/bin/lnms

**Comment by murrant** [comment]
In that case the check should succeed:

https://github.com/librenms/librenms/blob/master/LibreNMS/Validations/System.php#L41

**Comment by crazy-max** [comment]
@murrant https://github.com/librenms/docker/blob/master/rootfs/usr/local/bin/lnms is owned by root nad the php-fpm process is run as librenms user that must be the issue. Also as I can see in this `System.php` there is no bash_completion or logrotate. Everything is done through Docker.
