### ISSUE TITLE
Librenms discovery route exception

### ISSUE THREAD

**Issue by kuizen** [librenms/docker#157]
### Behaviour
Hello, 
I have common "compose" setup
https://github.com/librenms/docker/tree/master/examples/compose

all starts fine but after some time(24h) dispatcher stops polling - At this point i see in web Ui at /polling that 
"Device Actioned Last interval" is 0.

Started checking logs. And i see next exceptions which repeats over time:

```
[2021-01-20 02:12:13] production.ERROR: Cannot unset string offsets {"exception":"[object] (Error(code: 0): Cannot unset string offsets at /opt/librenms/includes/discovery/route.inc.php:265)
[stacktrace]
#0 /opt/librenms/includes/discovery/functions.inc.php(165): include()
#1 /opt/librenms/discovery.php(116): discover_device(Array, false)
#2 {main}
"}
```

I checked this line:
/opt/librenms/includes/discovery/route.inc.php:265
Its smth about mpls discovery. I disabled mpls discovery_module and restarted. But exceptions appear again.
Noob in php, so need your help with this issue. 

### Configuration

* Docker version 18.09.2, build 6247962
* docker-compose version 1.18.0, build 8dd22a9
* Platform Centos 7. 
   Virtualization: vmware
   Linux 3.10.0-957.5.1.el7.x86_64
   

### Docker info

```
Containers: 8
 Running: 8
 Paused: 0
 Stopped: 0
Images: 11
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-957.5.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 9.607GiB
Name: test
ID: W5JF:NV4G:JOOS:PB2D:B2N6:YK6T:6JIW:PRY2:VW7H:ZROU:AI7B:B7XA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
HTTPS Proxy: http://192.168.1.73:8080/
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Comment by kuizen** [comment]
![image](https://user-images.githubusercontent.com/53814499/105170571-c9a6c700-5b25-11eb-8e26-260122b5abe6.png)

Logs when problem occurs:
'''
/opt/librenms/poller.php 261 2021-01-20 12:14:30 - 1 devices polled in 13.16 secs
/opt/librenms/poller.php 262 2021-01-20 12:14:30 - 1 devices polled in 13.17 secs
/opt/librenms/poller.php 280 2021-01-20 12:14:30 - 1 devices polled in 13.16 secs
/opt/librenms/poller.php 291 2021-01-20 12:14:31 - 1 devices polled in 13.15 secs
/opt/librenms/poller.php 269 2021-01-20 12:14:31 - 1 devices polled in 13.15 secs
/opt/librenms/poller.php 144 2021-01-20 12:14:32 - 1 devices polled in 13.12 secs
/opt/librenms/poller.php 337 2021-01-20 12:14:32 - 1 devices polled in 13.15 secs
/opt/librenms/poller.php 332 2021-01-20 12:14:33 - 1 devices polled in 13.15 secs
[2021-01-20 12:14:37] production.ERROR: Cannot unset string offsets {"exception":"[object] (Error(code: 0): Cannot unset string offsets at /opt/librenms/includes/discovery/route.inc.php:265)
[stacktrace]
#0 /opt/librenms/includes/discovery/functions.inc.php(165): include()
#1 /opt/librenms/discovery.php(116): discover_device(Array, false)
#2 {main}
"}
/opt/librenms/poller.php 75 2021-01-20 12:15:09 - 1 devices polled in 46.48 secs
[2021-01-20 12:15:29] production.ERROR: Cannot unset string offsets {"exception":"[object] (Error(code: 0): Cannot unset string offsets at /opt/librenms/includes/discovery/route.inc.php:265)
[stacktrace]
#0 /opt/librenms/includes/discovery/functions.inc.php(165): include()
#1 /opt/librenms/discovery.php(116): discover_device(Array, false)
#2 {main}
"}
[2021-01-20 12:15:39] production.ERROR: Cannot unset string offsets {"exception":"[object] (Error(code: 0): Cannot unset string offsets at /opt/librenms/includes/discovery/route.inc.php:265)
[stacktrace]
#0 /opt/librenms/includes/discovery/functions.inc.php(165): include()
#1 /opt/librenms/discovery.php(116): discover_device(Array, false)
#2 {main}
"}
'''

If i check inside container when in fault state:
![image](https://user-images.githubusercontent.com/53814499/105171386-d546bd80-5b26-11eb-9b75-99f32ed19e32.png)

And after execution of the command "docker restart librenms_dispatcher" all backs to normal for some time. Inside container i see alot of monitoring processes

**Comment by crazy-max** [comment]
Doesn't seem related to the Docker image. Suggest to create a post on https://community.librenms.org/.
