### ISSUE TITLE
Enable weathermap plugin. 

### ISSUE THREAD

**Issue by sk4mi** [librenms/docker#16]
Hello !

I’m trying to install weathermap on docker.

First for all who want to try, you must add the packet  php7-mysqli. Weathermap internal needs this dep. 

I followed docs on a fresh install, it works. 
But when trying in docker, the editor works but it can’t generate maps in output folder. 

How to:
* install properly plugin in docker image ?
* run cron on side-car?

Thanks for all your work. 
Sk4mi.

**Comment by crazy-max** [comment]
Hi @sk4mi,

I have take a look about your issue and it seems like the plugin has to be refactored a little bit for Docker. In particular the [configs path](https://github.com/librenms-plugins/Weathermap/search?l=PHP&q=configs) which is today hardcoded and must be moved to something like `/data/weathermap` and use pdo instead of mysqli.

The best way would be to first create an issue on the [plugin repository](https://github.com/librenms-plugins/Weathermap) to implement these changes and then we can move forward on the Docker image.

I will talk to @laf about this.

Thnaks for your input!

**Comment by murrant** [comment]
mysqlnd satisfies the mysqli extension.  You do not need php7-mysqli.

**Comment by crazy-max** [comment]
@murrant There is a mysqli_connect error when I try to click on `[Pick from LibreNMS]` :

![image](https://user-images.githubusercontent.com/1951866/51363356-e4c64280-1ad7-11e9-88d1-0df18e4a2d7e.png)

**Comment by daemienb** [comment]
Hi All,

did this ever get implemented? would be great to get this enabled.

Thanks,
Daemien

**Comment by murrant** [comment]
The msqli bug was fixed, but I don't think the changes that were needed were ever implemented.

**Comment by sk4mi** [comment]
I think it's not implemented, i need to rebuild own image to activate it out-of-the-box.

As soon as i got free time i'll PR for this issue.

**Comment by daemienb** [comment]
excellent thanks Team!

**Comment by daemienb** [comment]
HI Team,

have you had chance to PR this yet?

**Comment by georgejprodec** [comment]
Would love to see this

**Comment by setiseta** [comment]
so it seems, that there is not much to do.
you need to mount the plugins dir to you host like:
      - "./librenms/plugins:/opt/librenms/html/plugins"

then go to this dir and clone the librenms version of weathermap:
git clone https://github.com/librenms-plugins/Weathermap.git

but in the librenms image there is php pear missing, maybe this could be added?
apk add php7.pear

then set some permissions as displayed in librenms after plugin activation.

one thing i'm currently missing is how to integrate the cron best, cause this is no on my test install over the dispatcher, maybe any hint how we can add there another job?
workaround would be a cronjob on the host which triggers a docker command to update the maps, but its ugly.
if i get some starting point with the dispatcher i will be able to open a pr.

**Comment by murrant** [comment]
A PR to add that to the dispatcher won't be accepted upstream.  Weathermap is a third party plugin and also plugins are deprecated.

**Comment by setiseta** [comment]
thx @murrant for the information. i haven't recognised that this is deprecated.

so to use it over dispatcher ( or legacy cron) without changing something on the system or cron entries, i have "missused" the service system now.
add the plugin volume mount to the librenms and the dispatcher/cron container.

i added a new check_weathermapupdate
```
#!/usr/bin/env bash
/opt/librenms/html/plugins/Weathermap/map-poller.php

if [ $? -eq 0 ]
then
  echo "Weathermap Update done at $(date)"
  exit 0
fi

echo "Weathermap Update failed at $(date)"
exit 2
```
and setup this service on a machine. so the dispatcher is calling the update over the service check.
last thing missing is the php7-pear pakage on the librenms docker image.
but i don't think this will be added.(or am i wrong)
So @sk4mi if you want it to run you may build your own image with this as base and add the php7-pear package.

**Comment by crazy-max** [comment]
@setiseta I have create a PR for this feature #81. Will be merged soon.
