### ISSUE TITLE
Weathermap 404 Not found nginx error

### ISSUE THREAD

**Issue by subin8848** [librenms/docker#163]
#### Steps to reproduce this issue

1. Create map using Weathermap editor
2. Try to view created weathermap 

#### Expected behaviour

> Created weathermap should be shown

#### Actual behaviour

> 404 Not found nginx page appears

The problem could also be seen in Docker Playground.

**Comment by absentrecall** [comment]
I got the same 404 Not Found error for the Weathermap page after updating to 21.2.0-r0 release.

Weathermap was working before the update.

I was able to get Weathermap working again with the following changes to the librenms container:

docker exec -it librenms /bin/sh
chown librenms:librenms /opt/librenms/html/plugins/Weathermap/output/index.php

This is just a temporary workaround.  I assume the fix would require a change to the librenms docker image.
