### ISSUE TITLE
s6-overlay not sending TERM/KILL on exit 1

### ISSUE THREAD

**Issue by Random6554** [librenms/docker#164]
### Behaviour

The s6-overlay does not send the stage 3 TERM and KILL signals on exit 1 codes from the init scripts found in https://github.com/librenms/docker/tree/master/rootfs/etc/cont-init.d/

This is breaking a few things in my environment as the containers run healthily when under the hood there are errors. This is affecting Redis for me right now, I need the container to die if they spin-up without the correct ENVs vars set. 

#### Steps to reproduce this issue

Spin the docker-compose example and match any condition in the init scripts that exit 1. The condition fails on the init script correctly but the s6-overlay does not kill the container as expected.

#### Expected behaviour

librenmsv2-dispatcher-00    | [cont-init.d] 05-svc-dispatcher.sh: exited 1.
librenmsv2-dispatcher-00    | [cont-finish.d] executing container finish scripts...
librenmsv2-dispatcher-00    | [cont-finish.d] done.
librenmsv2-dispatcher-00    | [s6-finish] waiting for services.
librenmsv2-dispatcher-00    | [s6-finish] sending all processes the TERM signal.
librenmsv2-dispatcher-00    | [s6-finish] sending all processes the KILL signal and exiting.
librenmsv2-dispatcher-00 exited with code 1

#### Actual behaviour

librenmsv2-dispatcher-00    | [cont-init.d] 05-svc-dispatcher.sh: exited 1.
librenmsv2-dispatcher-00    | [cont-init.d] 06-svc-syslogng.sh: executing... 
librenmsv2-dispatcher-00    | [cont-init.d] 06-svc-syslogng.sh: exited 0.
librenmsv2-dispatcher-00    | [cont-init.d] 07-svc-cron.sh: executing... 
librenmsv2-dispatcher-00    | [cont-init.d] 07-svc-cron.sh: exited 0.
librenmsv2-dispatcher-00    | [cont-init.d] ~-socklog: executing... 
librenmsv2-dispatcher-00    | [cont-init.d] ~-socklog: exited 0.
librenmsv2-dispatcher-00    | [cont-init.d] done.
librenmsv2-dispatcher-00    | [services.d] starting services
librenmsv2-dispatcher-00    | [services.d] done.

### Configuration

Tested using the docker-compose.

I can only repro this issue on 21.1.0 and not on 1.70.1 and 1.69, 1.68.

I have been through the change logs and I don't see anything that would specifically affect this behavior.

I don't know much about s6 but I also don't really understand how flipping the version can break this given that we pull s6 from the upstream docker container and both 21.1.0 and 1.70.1 are using crazymax/alpine-s6:3.12.

**Comment by crazy-max** [comment]
@Random6554 Thanks about your report, that could be linked to the [latest release of s6](https://github.com/crazy-max/docker-alpine-s6/releases/tag/2.2.0.1-r0) used here.

**Comment by crazy-max** [comment]
@Random6554 Upstream issue. See just-containers/s6-overlay#324. I move this issue to the alpine-s6 repo.
