### ISSUE TITLE
Sudo Not Installed

### ISSUE THREAD

**Issue by angdigi** [librenms/docker#17]
Fresh install of librenms and trying to ensure results of validate are satisfied.

Running ./daily.sh by hand results in this...
`/opt/librenms # ./daily.sh
Re-running /opt/librenms/daily.sh as librenms user
./daily.sh: line 166: sudo: command not found
/opt/librenms #`

How should I proceed in fixing this?

**Comment by crazy-max** [comment]
`docker-compose exec --user librenms librenms <command>` is the way to go

**Comment by angdigi** [comment]
So I don't have docker-compose installed on this machine. I use dockerman which is an unraid thing. I realize that's not supported, but I guess my question is around the specific error on line 166.

Are you suggesting running a different command for ./daily.sh or trying to fix that particular issue with the script?

**Comment by crazy-max** [comment]
What's the purpose to run `daily.sh` ? Autoupdate for LibreNMS [is disabled](https://github.com/librenms/docker/blob/master/entrypoint.sh#L156) on this image.

**Comment by angdigi** [comment]
Well...I suppose I missed that part. I was just trying to resolve the errors/warnings from the validation..

**Comment by crazy-max** [comment]
Can you post the output of validation ?

**Comment by angdigi** [comment]
`/opt/librenms # ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 1.47
DB Schema | 275
PHP       | 7.2.13
MySQL     | 10.3.12-MariaDB-1:10.3.12+maria~bionic-log
RRDTool   | 1.7.0
SNMP      | NET-SNMP 5.7.3
====================================

[OK]    Composer Version: 1.8.0
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
[FAIL]  The poller has never run or you are not using poller-wrapper.py, check the cron job.
[WARN]  Some devices have not been polled in the last 5 minutes. You may have performance issues.
        [FIX]:
        Check your poll log and see: http://docs.librenms.org/Support/Performance/
        Devices:
         pfsense.local.lan
[FAIL]  Discovery has never run. Check the cron job
[WARN]  IPv6 is disabled on your server, you will not be able to add IPv6 devices.
[WARN]  Your install is over 24 hours out of date, last update: Sun, 30 Dec 2018 14:29:16 +0000
        [FIX]:
        Make sure your daily.sh cron is running and run ./daily.sh by hand to see if there are any errors.
[WARN]  Your local git branch is not master, this will prevent automatic updates.
        [FIX]:
        You can switch back to master with git checkout master
[WARN]  Your local git contains modified files, this could prevent automatic updates.
        [FIX]:
        You can fix this with ./scripts/github-remove
        Modified Files:
         bootstrap/cache/.gitignore
         storage/app/.gitignore
         storage/app/public/.gitignore
         storage/debugbar/.gitignore
         storage/framework/cache/.gitignore
         storage/framework/sessions/.gitignore
         storage/framework/testing/.gitignore
         storage/framework/views/.gitignore
         storage/logs/.gitignore
[FAIL]  Some folders have incorrect file permissions, this may cause issues.
        [FIX]:
        sudo chown -R librenms:librenms /opt/librenms
        sudo setfacl -d -m g::rwx /data/rrd /data/logs /opt/librenms/bootstrap/cache/ /opt/librenms/storage/
        sudo chmod -R ug=rwX /data/rrd /data/logs /opt/librenms/bootstrap/cache/ /opt/librenms/storage/
        Files:
         /opt/librenms/storage/framework/sessions/Ng6WYLWj5RIUSVlOKH1s13Iq1TpGvaXXdIZ3U59f
/opt/librenms #`

**Comment by murrant** [comment]
@crazy-max ./daily.sh does a lot more that just update, mostly maintenance tasks to keep the database from blowing up.  Docs has details.

**Comment by crazy-max** [comment]
@murrant As I see [in the doc](https://docs.librenms.org/General/Updating/#manual-update), this script will update both the core LibreNMS files but also update the database structure if updates are available but as autoupdate [is disabled](https://github.com/librenms/docker/blob/master/entrypoint.sh#L156), it will only do [this task](https://github.com/librenms/librenms/blob/master/daily.sh#L182-L186) right ?
