### ISSUE TITLE
Librenms plugin folder

### ISSUE THREAD

**Issue by danielmbrown603** [librenms/docker#171]
### Behaviour
I copied the following plugin to the monitoring-plugin folder and librenms isn't detecting it. 
https://gitlab.com/sindrel/librenms-overview

#### Steps to reproduce this issue

1.Follow steps from link

#### Expected behaviour

> It should pop-up under Overview/Plugins/Plugin Admin from the web interface

```

**Comment by crazy-max** [comment]
@danielmbrown603 

`monitoring-plugin` is not for LibreNMS plugins but Nagios ones. See https://github.com/librenms/docker/blob/master/doc/notes/additional-monitoring-plugins.md for more info.

But we could add this feature to allow adding LibreNMS plugins in this image if you want.

**Comment by danielmbrown603** [comment]
Oh, that makes sense. That helps with why I couldn’t get it to work.  

That would be so awesome to add that feature. Thank you for the reply and help!

**Comment by crazy-max** [comment]
@danielmbrown603 Done, see https://github.com/librenms/docker/blob/master/doc/notes/plugins.md

**Comment by danielmbrown603** [comment]
I'll give it a go. Thank you!

**Comment by haydenseitz** [comment]
This is awesome, thanks @crazy-max!
