### ISSUE TITLE
./daily.sh not working because sudo is not installed

### ISSUE THREAD

**Issue by Themimitoof** [librenms/docker#172]
### Behaviour

After being confronted with a disk space problem on my LibreNMS instance, I spotted that the `daily.sh` script fails every day. After investigating, I spotted that sudo is not available in the dispatcher container (and it's really nice to not have `sudo` in the containers!) but the `daily.sh` script need `sudo`.

Temporarily, I installed sudo in the dispatcher container (see _Workaround part_) in order to have my instance back. Probably is nothing to do in this repository and probably create a PR in `librenms` repo to use `sh` command instead of `sudo` as fallback if `sudo` is not installed.

#### Steps to reproduce this issue

1. Run `docker-compose exec dispatcher ./daily.sh`
 
#### Expected behaviour

```
xxx@nagoya:/opt/librenms# docker-compose exec dispatcher ./daily.sh
Re-running /opt/librenms/daily.sh as librenms user
Updating SQL-Schema                                OK
Cleaning up DB                                     OK
```

#### Actual behaviour

```
xxx@nagoya:/opt/librenms# docker-compose exec dispatcher ./daily.sh
Re-running /opt/librenms/daily.sh as librenms user
./daily.sh: line 264: sudo: command not found
```

### Workaround

Add `sudo` to the `apk add` command in the `Dockerfile` (or temporarily use `docker-compose exec dispatcher apk add sudo`). The other possible workaround is to update this line (https://github.com/librenms/librenms/blob/master/daily.sh#L264)

**Comment by murrant** [comment]
./daily.sh should not be run as root.

**Comment by Themimitoof** [comment]
Hi @murrant 

I'm completely agree with you (and I notice it in my second phrase of the issue!). 

> I spotted that sudo is not available in the dispatcher container **(and it's really nice to not have sudo in the containers!)** but the daily.sh script need sudo.

I think I mistitled the Workaround section of my issue (in fact is **my** temporary workaround, not my suggestion to fix the issue). If you read back the second paragraph of the issue, I said that probably we should make a PR on LibreNMS repository and **NOT installing sudo or running the script as root**.

> Temporarily, I installed sudo in the dispatcher container (see Workaround part) in order to have my instance back. **Probably is nothing to do in this repository and probably create a PR in librenms repo to use sh command instead of sudo as fallback if sudo is not installed.**

**Comment by murrant** [comment]
The only reason daily.sh uses sudo is legacy reasons.  Installs used root at one time.  To prevent daily.sh from running as root without breaking current installs, sudo was used.  Could probably remove sudo usage as people with that old of installs are no longer updating.  Feel free to send PR to main repo.

**Comment by crazy-max** [comment]
@Themimitoof https://github.com/librenms/docker/issues/17#issuecomment-455625395
