### ISSUE TITLE
Custom configuration not applied

### ISSUE THREAD

**Issue by nickbouwhuis** [librenms/docker#18]
Hi there!

I've been using LibreNMS for a while, and recently moved to a docker deployment. I used custom configuration options in my previous installation, but they don't seem to work in the Docker version.

As per the [README.md](https://github.com/librenms/docker#edit-configuration), I created the following file in data/config/locationmapping.php:
```
<?php
$config['location_map']['Home'] = "Stationsplein 33, 7511 JD Enschede";
```

When I visit https://[librenms]/settings/, I can see it has been picked up:
![config page](https://i.imgur.com/tlopOI4.png)

However, if I then check https://[librenms]/devices, I see the following. [If I'm not mistaken](https://docs.librenms.org/Support/Configuration/#location-mapping), "Home" should have been replaced with my configuration setting.
![devices page](https://i.imgur.com/prxYG83.png)

Am I missing something? Or is there something broken?

Thanks in advance!

**Comment by murrant** [comment]
Isn't it easier to just edit the locations then messing with that wonky thing.

![image](https://user-images.githubusercontent.com/39462/51433189-0116cc00-1c0b-11e9-9205-50d2640181e2.png)

**Comment by nickbouwhuis** [comment]
> Isn't it easier to just edit the locations then messing with that wonky thing.

That's not the point of this issue. For example, If I want to enable pushing data to InfluxDB, it's done the same way, and the same issue seems to be present.

**Comment by crazy-max** [comment]
@nickbouwhuis What is your version of LibreNMS before your migration to Docker ?

**Comment by crazy-max** [comment]
Ok then what was LibreNMS version of your old install ?

**Comment by nickbouwhuis** [comment]
> Ok then what was LibreNMS version of your old install ?

My bad. It was on 1.45-59-gc5bb609 before I turned it off. Had to dig up my old VM to check.

**Comment by crazy-max** [comment]
Ok thanks, can you check if this behaviour occurrs with [1.45 tag](https://hub.docker.com/r/librenms/librenms/tags) ?

**Comment by nickbouwhuis** [comment]
I can confirm this issue is also present on the 1.45 tag. 

![image](https://user-images.githubusercontent.com/2922075/51439622-61fedc80-1cbd-11e9-97af-3331f597d7a0.png)

**Comment by nickbouwhuis** [comment]
> Ok thanks, can you check if this behaviour occurrs with [1.45 tag](https://hub.docker.com/r/librenms/librenms/tags) ?

This issue doesn't occur on the 1.45 tag. The custom configuration is applied here.

![image](https://user-images.githubusercontent.com/2922075/51439664-cd48ae80-1cbd-11e9-880a-9855ac2e06dd.png)

**Comment by nickbouwhuis** [comment]
Can't pinpoint why, but after some testing and rebuiliding, and placeing data back, it suddenly started working again.
