### ISSUE TITLE
Rpi Issue with MariaDB container 

### ISSUE THREAD

**Issue by rphanikrishna** [librenms/docker#207]
Error while pulling MariaDB for Rpi 

1.git clone https://github.com/librenms/docker.git docker-librenms
2.docker-compose up -d

#### Expected behaviour

No matching docker container for arm/v7

#### Actual behaviour

Creating network "compose_default" with the default driver
Pulling db (mariadb:10.5)...
10.5: Pulling from library/mariadb
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries

### Configuration

* Docker version (type `docker --version`) :Docker version 20.10.6, build 370c289
* Docker compose version if applicable (type `docker-compose --version`) : docker-compose version 1.29.2, build unknown
* Platform (Debian 9, Ubuntu 18.04, ...) : Pi OS lite : release 2021-05-07
* System info (type `uname -a`) : Linux raspberrypi 5.10.17-v7+ #1421 SMP Thu May 27 13:59:01 BST 2021 armv7l GNU/Linux
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

**Comment by crazy-max** [comment]
@rphanikrishna As stipulated in their [README](https://hub.docker.com/_/mariadb/), only amd64, arm64v8, ppc64le platforms are available. You could install [Ubuntu server](https://ubuntu.com/download/raspberry-pi).
