### ISSUE TITLE
alert templates usage examples

### ISSUE THREAD

**Issue by mkurjanski** [librenms/docker#212]
Hi, could you please expand the documentation with some examples how to add the alert templates into /data/alert-templates/ ?

**Comment by murrant** [comment]
Question needs more clarification.

**Comment by ryanmerolle** [comment]
I too am confused about what format the alert-templates should be stored in.  I mean what is the file type it needs to be even stored as?

**Comment by murrant** [comment]
The given link in the docker documentation explains what they are https://docs.librenms.org/Alerting/Templates/#base-templates
These files are for creating a shared layout for all alert templates. If you scroll up it explains all templates are in blade format.
If you just want to use templates, you must do so from within the LibreNMS interface.
