### ISSUE TITLE
Unable to add devices using SNMP on IPv6 (udp6 transport)

### ISSUE THREAD

**Issue by inferno480** [librenms/docker#214]
### Behaviour

Unable to get LibreNMS to poll SNMP via IPv6 (udp6 transport), IPv4 works fine.  Confirmed the IPv6 address assigned to the container is valid and has full network reachability, including ICMP to the devices that will not add.

#### Steps to reproduce this issue
(xxxx:yyyy:zzzz of course replaced with my real IPv6 addresses)

1.  ./addhost.php xxxx:yyyy:zzzz:100::10 test v2c 161 udp6 
2. snmpwalk -c test -v 2c xxxx:yyyy:zzzz:100::10 /* succeeds, expected output returned */
3. Sniffed all IPv6 traffic to the zzzz:100::10 device port using Wireshark, and only see IPv6 SNMP if sent via snmpwalk.

#### Expected behaviour

> Device should be added to LibreNMS successfully because the container can successfully SNMPwalk to the same device with the same SNMP settings.

#### Actual behaviour

> Could not connect to xxxx:yyyy:zzzz:100::10, please check the snmp details and snmp reachability
SNMP v2c: No reply with community test
SNMP v2c: No reply with community public

### Configuration

* Docker version (type `docker --version`) :  Docker version 20.10.7, build f0df350
* Docker compose version if applicable (type `docker-compose --version`) : docker-compose version 1.25.0, build unknown
* Platform (Debian 9, Ubuntu 18.04, ...) : Ubuntu 20.10
* System info (type `uname -a`) : Linux docker 5.8.0-59-generic #66-Ubuntu SMP Thu Jun 17 00:46:01 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

docker-compose.yaml (IPv6 IP edited), I am running a macvlan setup:

version: '3.3'
services:
  db:
    image: mariadb:10.5
    container_name: librenms_db
    command:
      - "mysqld"
      - "--innodb-file-per-table=1"
      - "--lower-case-table-names=0"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - "/mnt/data/librenms/db:/var/lib/mysql"
    environment:
      - "TZ=${TZ}"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    restart: always
    networks:
      macvlan100:
        ipv4_address: 172.16.100.51
        ipv6_address: xxxx:yyyy:zzzz:100::51
    hostname: db

  memcached:
    image: memcached:alpine
    container_name: librenms_memcached
    environment:
      - "TZ=${TZ}"
    restart: always
    networks:
      macvlan100:
        ipv4_address: 172.16.100.52
        ipv6_address: xxxx:yyyy:zzzz:100::52
    hostname: memcached

  redis:
    image: redis:5.0-alpine
    container_name: librenms_redis
    environment:
      - "TZ=${TZ}"
    restart: always
    networks:
      macvlan100:
        ipv4_address: 172.16.100.53
        ipv6_address: xxxx:yyyy:zzzz:100::53
    hostname: redis

  msmtpd:
    image: crazymax/msmtpd:latest
    container_name: librenms_msmtpd
    env_file:
      - "/mnt/data/librenms/msmtpd.env"
    restart: always
    networks:
      macvlan100:
        ipv4_address: 172.16.100.54
        ipv6_address: xxxx:yyyy:zzzz:100::54
    hostname: msmtpd

  librenms:
    image: librenms/librenms:latest
    container_name: librenms
    hostname: librenms
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - db
      - memcached
      - msmtpd
    volumes:
      - "/mnt/data/librenms:/data"
    env_file:
      - "/mnt/data/librenms/librenms.env"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=${MYSQL_HOST}"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
      - "REDIS_HOST=xxxx:yyyy:zzzz:100::53"
      - "REDIS_PORT=6379"
      - "REDIS_DB=0"
    restart: always
    networks:
      macvlan100:
        ipv4_address: 172.16.100.55
        ipv6_address: xxxx:yyyy:zzzz:100::55

  dispatcher:
    image: librenms/librenms:latest
    container_name: librenms_dispatcher
    hostname: librenms-dispatcher
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - librenms
      - redis
    volumes:
      - "/mnt/data/librenms:/data"
    env_file:
      - "/mnt/data/librenms/librenms.env"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=${MYSQL_HOST}"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
      - "DISPATCHER_NODE_ID=dispatcher1"
      - "REDIS_HOST=xxxx:yyyy:zzzz:100::53"
      - "REDIS_PORT=6379"
      - "REDIS_DB=0"
      - "SIDECAR_DISPATCHER=1"
    restart: always
    networks:
      macvlan100:
        ipv4_address: 172.16.100.56
        ipv6_address: xxxx:yyyy:zzzz:100::56

  syslogng:
    image: librenms/librenms:latest
    container_name: librenms_syslogng
    hostname: librenms-syslogng
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - librenms
    volumes:
      - "/mnt/data/librenms:/data"
    env_file:
      - "/mnt/data/librenms/librenms.env"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=${MYSQL_HOST}"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
      - "REDIS_HOST=xxxx:yyyy:zzzz:100::53"
      - "REDIS_PORT=6379"
      - "REDIS_DB=0"
      - "SIDECAR_SYSLOGNG=1"
    restart: always
    networks:
      macvlan100:
        ipv4_address: 172.16.100.50
        ipv6_address: xxxx:yyyy:zzzz:100::50

networks:
   macvlan100:
     external: true
---

.env file:

TZ=America/Detroit
PUID=1000
PGID=1000

MYSQL_HOST=db
MYSQL_DATABASE=librenms
MYSQL_USER=librenms
MYSQL_PASSWORD=somelongpassword

### Docker info

```
> Output of command `docker info`
```

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 11
  Running: 9
  Paused: 0
  Stopped: 2
 Images: 46
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.8.0-59-generic
 Operating System: Ubuntu 20.10
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.33GiB
 Name: docker
 ID: V3TV:KBAG:Y5YB:YJ24:C5NK:GRQG:ZNFR:PC3Z:YIHC:HTPE:GUNX:C25S
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

### Logs

```
> Container logs (set LOG_LEVEL to debug if applicable)
```
(nothing new seems to appear in the JSON log for the container when I attempt to add a device using addhost.php)

**Comment by murrant** [comment]
Can you run ./validate.php inside the container?

**Comment by inferno480** [comment]
Looks like it wants some db fixes... should I run them?  I am still have to add IPv4 devices even with these FAILs.

bash-5.1$ ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 21.6.0
DB Schema | 2021_25_01_0127_create_isis_adjacencies_table (210)
PHP       | 7.4.19
Python    | 3.8.10
MySQL     | 10.5.11-MariaDB-1:10.5.11+maria~focal
RRDTool   | 1.7.2
SNMP      | NET-SNMP 5.9
====================================

[OK]    Installed from the official Docker image; no Composer required
[OK]    Database connection successful
[FAIL]  Database: incorrect column (notifications/datetime)
[FAIL]  Database: incorrect column (users/created_at)
[FAIL]  We have detected that your database schema may be wrong, please report the following to us on Discord (https://t.libren.ms/discord) or the community site (https://t.libren.ms/5gscd):
        [FIX]:
        Run the following SQL statements to fix.
        SQL Statements:
         ALTER TABLE `notifications` CHANGE `datetime` `datetime` timestamp NOT NULL DEFAULT '1970-01-02 00:00:00' ;
         ALTER TABLE `users` CHANGE `created_at` `created_at` timestamp NOT NULL DEFAULT '1970-01-02 00:00:01' ;
[WARN]  Updates are managed through the official Docker image
bash-5.1$

**Comment by murrant** [comment]
@inferno480 Is the address you are trying to add a link local address? (fe80, because those are not pingable by default)
Try using this command instead: `lnms device:add --v2c -t udp6 -c test xxxx:yyyy:zzzz100:10`

**Comment by inferno480** [comment]
Hello, sorry for the long delay, been rather busy -- here is the output of that command.  Nope, I am not using link-local addresses, I just edited out the first portion of my IPv6 address for privacy.  In the case below I search & replaced my first three "real" sections with "dead:beef:dead".

bash-5.1# lnms device:add --v2c -t udp6 -c test dead:beef:dead:100::10
Could not connect to dead:beef:dead:100::10, please check the snmp details and snmp reachability
SNMP v2c: No reply with community test
SNMP v2c: No reply with community public

bash-5.1# ping dead:beef:dead:100::10
PING dead:beef:dead:100::10(dead:beef:dead:100::10) 56 data bytes
64 bytes from dead:beef:dead:100::10: icmp_seq=1 ttl=64 time=2.68 ms
64 bytes from dead:beef:dead:100::10: icmp_seq=2 ttl=64 time=1.48 ms
64 bytes from dead:beef:dead:100::10: icmp_seq=3 ttl=64 time=0.704 ms
^C
--- dead:beef:dead:100::10 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2002ms
rtt min/avg/max/mdev = 0.704/1.620/2.677/0.811 ms

bash-5.1# snmpwalk -c test -v 2c dead:beef:dead:100::10
SNMPv2-MIB::sysDescr.0 = STRING: Cisco IOS Software, C1000 Software (C1000-UNIVERSALK9-M), Version 15.2(7)E3k, RELEASE SOFTWARE (fc2)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2020 by Cisco Systems, Inc.
Compiled Fri 04-Dec-20 00:51 by prod_rel_team
SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.9.1.2897
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (292723013) 33 days, 21:07:10.13

([etc, etc] -- full snmpwalk completes)

The LibreNMS container is on the same VLAN / ethernet segment as the device I am trying to add, there are no ACLs or firewall rules being traversed:

bash-5.1# ip -6 addr show dev eth0
38: eth0@if5: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 state UP
    inet6 dead:beef:dead:100::55/64 scope global flags 02
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe10:6437/64 scope link
       valid_lft forever preferred_lft forever

I am able to reach the outside Internet as well without issue:

bash-5.1# ping www.google.com
PING www.google.com(sea30s01-in-x04.1e100.net (2607:f8b0:400a:801::2004)) 56 data bytes
64 bytes from sea30s01-in-x04.1e100.net (2607:f8b0:400a:801::2004): icmp_seq=1 ttl=107 time=59.8 ms
64 bytes from sea30s01-in-x04.1e100.net (2607:f8b0:400a:801::2004): icmp_seq=2 ttl=107 time=59.8 ms
64 bytes from sea30s01-in-x04.1e100.net (2607:f8b0:400a:801::2004): icmp_seq=3 ttl=107 time=59.9 ms
64 bytes from sea30s01-in-x04.1e100.net (2607:f8b0:400a:801::2004): icmp_seq=4 ttl=107 time=59.9 ms
^C
--- www.google.com ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 59.838/59.855/59.885/0.017 ms

* Side note/for the record, I did also attempt communicating to the device using the link-local address, just to see if it worked -- I am able to ping, but the snmpwalk fails, I did not bother to attempt to use librenms to add it  :-)

**Comment by murrant** [comment]
I think this will be fixed in the next release: https://github.com/librenms/librenms/pull/13130
