### ISSUE TITLE
Can't create admin user

### ISSUE THREAD

**Issue by Symness** [librenms/docker#226]
When I install librenms using `docker-compose up -d`, everything seems to be fine.
Then, I start `docker-compose logs -f` command, and I get this in logs :

```
librenms      | Creating admin user...
librenms      |
librenms      | In LnmsCommand.php line 113:
librenms      |
librenms      |   array_merge(): Expected parameter 1 to be an array, string given
```
I tried using this command, but the result is the same:
`docker-compose exec librenms lnms user:add admin`

```
In LnmsCommand.php line 113:

  array_merge(): Expected parameter 1 to be an array, string given
```

Any help ?
Thanks

OS : Debian 10 on Contabo VPS

**Comment by neitrinoweb** [comment]
I encounter the same issue.

Also, after 'docker-compose up d `  with default settings, librenms/librenms does not work, webui gives "Login Denied".

**Comment by lunarok** [comment]
same error with me, deploy the container yesterday, cannot log with default user as provided in doc
when I try to use lnms command, I got the error about expected array
maybe the latest release ?

**Comment by lunarok** [comment]
I pull version 21.8 of docker and now lnms command works

**Comment by murrant** [comment]
Fixed upstream

**Comment by crazy-max** [comment]
@murrant Do you have a link to the PR that fixes this issue?

**Comment by murrant** [comment]
https://github.com/librenms/librenms/pull/13265
