### ISSUE TITLE
GUI login not working for version 21.9.0 or above

### ISSUE THREAD

**Issue by sajiby3k** [librenms/docker#228]
Hi,

The tag latest or 21.9.0 - does not accept librenms/librenms as default login to the webgui.

Have the team documented somewhere what is the new username/password cobination?

Regards,

**Comment by murrant** [comment]
Issue is the admin user fails creation.  New release is pending.  In the meantime:
`docker-compose exec librenms /opt/librenms/adduser.php`

**Comment by JustasStankunas** [comment]
Hey @murrant @crazy-max, I just deployed fresh `librenms` deployment (latest tag) and had exact same issue. I presume that this fix had to be released already?

Service | Version
-- |  --
Version | 21.12.0
Database Schema | 2021_25_01_0129_isis_adjacencies_nullable (229)
Web Server |  
PHP | 7.4.26
Python | 3.9.5
MySQL | 10.6.5-MariaDB-1:10.6.5+maria~focal
Laravel | 8.65.0
RRDtool | 1.7.2
