### ISSUE TITLE
Auto Discovery using default SNMP community string (public) instead of the one defined in LIBRENMS_SNMP_COMMUNITY

### ISSUE THREAD

**Issue by zippanto** [librenms/docker#229]
### Behaviour
Auto Discovery using default SNMP community string (public) instead of the one defined in LIBRENMS_SNMP_COMMUNITY

The issue seems to be that during container initialisation there's no process to replace the "default" community string in config.php with the one defined in LIBRENMS_SNMP_COMMUNITY

#### Steps to reproduce this issue

1. Define LIBRENMS_SNMP_COMMUNITY in env / docker-compose file
2. Bring up service
3. Configure Auto Discovery (add a device + configure nets)
4. Devices discovered via Auto Discovery will be attempted to be added with the default SNMP community string (public)

#### Expected behaviour
Devices discovered through Auto Discovery should be added using the SNMP community string defined in the environmental variable LIBRENMS_SNMP_COMMUNITY

#### Actual behaviour
Instead it's being added with default SNMP community string (public)

### Configuration
* Docker version: 19.04

### Docker info

```
Server:
 Containers: 42
  Running: 13
  Paused: 0
  Stopped: 29
 Images: 99
 Server Version: 19.03.15
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 14faf1c20948688a48edb9b41367ab07ac11ca91
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.276-1.ph2-esx
 Operating System: VMware Photon OS/Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.65GiB
 Name: docker
 ID: LXVJ:XYB7:PA7Q:CZIX:XEAF:UN3I:G4QA:BF6E:664V:I2TO:PCU7:2DZ5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by crazy-max** [comment]
@MarlinMr

**Comment by MarlinMr** [comment]
I don't think I have worked on any parts that has to do with Auto Discovery?

But I would assume this is set by `03-config.sh`

```
# SNMP
echo "Updating SNMP community..."
file_env 'LIBRENMS_SNMP_COMMUNITY' 'librenmsdocker'
sed -i -e "s/RANDOMSTRINGGOESHERE/${LIBRENMS_SNMP_COMMUNITY}/" /etc/snmp/snmpd.conf
```
Is the "default string" set to 'librenmsdocker' and the sed command looks for `RANDOMSTRINGGOESHERE`?

**Comment by zippanto** [comment]
The above code

> I don't think I have worked on any parts that has to do with Auto Discovery?
> 
> But I would assume this is set by `03-config.sh`
> 
> ```
> # SNMP
> echo "Updating SNMP community..."
> file_env 'LIBRENMS_SNMP_COMMUNITY' 'librenmsdocker'
> sed -i -e "s/RANDOMSTRINGGOESHERE/${LIBRENMS_SNMP_COMMUNITY}/" /etc/snmp/snmpd.conf
> ```
> 
> Is the "default string" set to 'librenmsdocker' and the sed command looks for `RANDOMSTRINGGOESHERE`?

The issue is that nothing accounts for this line in config.php:
`$config['snmp']['community'] = array('public');`

And so Auto-Discovery just uses the SNMP community string 'public'

**Comment by MarlinMr** [comment]
Alright, that means it comes from the `Dockerfile`

```
&& cp config.php.default config.php \
```

That's this file https://github.com/librenms/librenms/blob/master/config.php.default

I would guess changing 

```
sed -i -e "s/RANDOMSTRINGGOESHERE/${LIBRENMS_SNMP_COMMUNITY}/" /etc/snmp/snmpd.conf
```
to
```
sed -i -e "s/public/${LIBRENMS_SNMP_COMMUNITY}/" /etc/snmp/snmpd.conf
```
would work, but it would not be ideal. 

Best would be to make some way to add `${LIBRENMS_SNMP_COMMUNITY}` to the `$config['snmp']['community']` array, as we would want to keep public in the discovery. I won't be able to fix it for a few days (at least some 48 hours), but I think that is probably the way to do it.

I guess we could make "our own" `config.php.default` for the docker image and ask for `${LIBRENMS_SNMP_COMMUNITY}` in there, but that might cause problems in the future when `config.php.default` in the main repo is changed.

**Comment by zippanto** [comment]
> Alright, that means it comes from the `Dockerfile`
> 
> ```
> && cp config.php.default config.php \
> ```
> 
> That's this file https://github.com/librenms/librenms/blob/master/config.php.default
> 
> I would guess changing
> 
> ```
> sed -i -e "s/RANDOMSTRINGGOESHERE/${LIBRENMS_SNMP_COMMUNITY}/" /etc/snmp/snmpd.conf
> ```
> 
> to
> 
> ```
> sed -i -e "s/public/${LIBRENMS_SNMP_COMMUNITY}/" /etc/snmp/snmpd.conf
> ```
> 
> would work, but it would not be ideal.
> 
> Best would be to make some way to add `${LIBRENMS_SNMP_COMMUNITY}` to the `$config['snmp']['community']` array, as we would want to keep public in the discovery. I won't be able to fix it for a few days (at least some 48 hours), but I think that is probably the way to do it.
> 
> I guess we could make "our own" `config.php.default` for the docker image and ask for `${LIBRENMS_SNMP_COMMUNITY}` in there, but that might cause problems in the future when `config.php.default` in the main repo is changed.

The community string is the correct one in snmpd.conf so I don't think anything needs to be changed there?

As I understood the purpose of the LIBRENMS_SNMP_COMMUNITY environmental variable is to pass the default SNMP community string to the docker environment / scripts to initialise the environment. So surely those scripts should replace the value in config.php (as there's no other way to change this value other than manually editing the file in the container - the LibreNMS web interface doesn't allow changing this value since it's set in config.php and lnms doesn't allow this setting to be changed either).

**Comment by murrant** [comment]
Also, if you set snmp settings in config.php they cannot be configured in the web ui or by lnms config:set

Now that you have brought that to my attention, I will be commenting all the lines in config.php.default

**Comment by murrant** [comment]
LIBRENMS_SNMP_COMMUNITY is to configure the community name in snmpd.conf

You should set snmp.community separately.

**Comment by zippanto** [comment]
> Also, if you set snmp settings in config.php they cannot be configured in the web ui or by lnms config:set
> 
> Now that you have brought that to my attention, I will be commenting all the lines in config.php.default

I'm not setting it, it's there by default and so it's unchangeable unless you edit the file manually in the container. Which I don't think is the right way to approach this.

> LIBRENMS_SNMP_COMMUNITY is to configure the community name in snmpd.conf
> 
> You should set snmp.community separately.

Okay that's fair enough I guess. Would it worth highlighting it at 
https://github.com/librenms/docker/blob/master/doc/docker/environment-variables.md ? I think it's not fully clear from the description that this is only for snmpd.conf (SNMP agent running on the container). I see other people also misreading the purpose of it https://github.com/librenms/docker/issues/129

In that case I guess this is a feature request instead of an issue.

**Comment by murrant** [comment]
Fixed in upstream... no settings are set by config.php.default now https://github.com/librenms/librenms/pull/13297

**Comment by zippanto** [comment]
Thanks. I guess this can be closed.
