### ISSUE TITLE
MEMORY_LIMIT not used by poller

### ISSUE THREAD

**Issue by JensForstmann** [librenms/docker#23]
My poller crashes with 

```
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 8192 bytes) in /opt/librenms/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 158

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 73728 bytes) in /opt/librenms/vendor/composer/ClassLoader.php on line 444
```

My MEMORY_LIMIT is set to 1024M, but the poller uses 128M for some reason.

Cause: The env var MEMORY_LIMIT is only written into `/etc/php7/php-fpm.d/www.conf` but not into `/etc/php7/php.ini` (which is used by the poller).

**Comment by JensForstmann** [comment]
I've created a PR, see #24

**Comment by crazy-max** [comment]
Good catch @JensForstmann :+1:
