### ISSUE TITLE
SMTP alert not working

### ISSUE THREAD

**Issue by ziodona85** [librenms/docker#232]
Hi,
i have a problem with alert mail.
I have configurated SMTP and if i do a transport test the mail was sent correctly.
I have configured transport and alert rule.
I can see in history alert the alarm.
But mail didn't work.
Could you help me?
My configuration is rrdcached-server in example.

Thanks.
Regards.

![smtp](https://user-images.githubusercontent.com/74834035/135831592-69762a54-1ae6-4fa8-9f0e-2973df52f632.png)
![transport](https://user-images.githubusercontent.com/74834035/135831597-245dbeac-019b-4a68-8215-b1cff7f90ce9.png)
![rule](https://user-images.githubusercontent.com/74834035/135834089-9ed1f111-5a34-435a-b357-91d0d74125bc.png)

**Comment by murrant** [comment]
Try setting your delay to 0.

**Comment by ziodona85** [comment]
I have solved problem disabling all template mail configured and redoing from zero the template. Thanks for support..
