### ISSUE TITLE
Traffic Bills Submenu Disappeared After Update to 21.10.1-r0

### ISSUE THREAD

**Issue by absentrecall** [librenms/docker#238]
Traffic Bills was configured and running with previous release 21.10.0-r0.  

After updating to latest release 21.10.1-r0, the Traffic Bills submenu under Ports disappeared.  Looking in Global Settings, I noticed the "enable_billing" config was set to false.  I added a custom config to set "enable_billing" = 1, then restarted the containers and the Traffic Bills submenu returned and I was able to access the previously configured bills.

I'm not sure why the librenms image update resulted in a change in the default "enable_billing" configuration but you may want to look into that.

**Comment by murrant** [comment]
If you set it to true in global settings, it will be persistent.
Curious though.
