### ISSUE TITLE
html emails not being generated? 

### ISSUE THREAD

**Issue by bcookatpcsd** [librenms/docker#243]
Thank you for taking the time to set all of this up. 

I did try manually to configure some of the included components.. and it was no where near as nice as this; so thank you in advance for your efforts.. 

I've chosen the rrdcached-server compose, and edited the .env for my TZ, I also tried to msmtp going.. but have my own relay which I currently have set. 

I did url [8000/alert-rules] and create rules from collection to get the default/stock values.. 
 - I have minimally tweaked some of these values to reduce the frequency of alerts.. 
 
via the url [8000/settings/global] I can see all the settings are what I think they should be.

allow_unauth_graphs true
allow_unauth_graphs_cidr [ "10.20.0.0/16" ]
email_html true

these two confuse me.. 
alerts.email.default_only
alerts.email.enable false

as I do receive emails.  

![image](https://user-images.githubusercontent.com/55087301/144486351-3c954507-449c-4b5c-8a42-3e4c7edbf2f2.png)

But this is an example of an email that arrives: 

![image](https://user-images.githubusercontent.com/55087301/144485794-cacd74d2-2371-4e40-96b4-f0cc4fbb7168.png)

And this is the page of the device events section: 

![image](https://user-images.githubusercontent.com/55087301/144486005-726056fc-b6c6-4c95-9226-639021ee1a73.png)

My question is, I do not see graphs in the emails that I receive, and I do not understand what the email that I received has to do with the events on this device page?

(does that make sense) 

Please let me know if I can provide or explain anything further.. 

Thank you in advance for your time..

**Comment by murrant** [comment]
The email, checks to see if the alert template includes any html and if it does not, it sends it as plain text.

Update your alert template to include html and you will get html.

**Comment by crazy-max** [comment]
Closing this issue since that should answer your question, but feel free to re-open if it doesn't. Thanks.
