### ISSUE TITLE
Compose file not compatible with armv7

### ISSUE THREAD

**Issue by billotronic** [librenms/docker#244]
### Behaviour
mariaDB does not support armv7 and compose deployment fails

#### Steps to reproduce this issue

1. wget the compose dir
2. docker-compose up

#### Expected behaviour

> librenms install and run

#### Actual behaviour

> `Pulling db (mariadb:10.5)...
10.5: Pulling from library/mariadb
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries`

### Configuration

* Docker version (type `docker --version`) : Docker version 20.10.11, build dea9396
* Docker compose version if applicable (type `docker-compose --version`) : docker-compose version 1.21.0, build unknown
* Platform (Debian 9, Ubuntu 18.04, ...) : Armbian 21.02.1 Buster
* System info (type `uname -a`) : 5.4.159-odroidxu4
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ... all default from github

### Docker info

```
> Output of command `docker info` Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)

Server:
 Containers: 16
  Running: 3
  Paused: 0
  Stopped: 13
 Images: 20
 Server Version: 20.10.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: wub304j4xqa82xsh3f7ayw7zg
  Is Manager: false
  Node Address: 192.168.0.101
  Manager Addresses:
   192.168.0.107:2377
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.159-odroidxu4
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: armv7l
 CPUs: 8
 Total Memory: 1.944GiB
 Name: PirateBaseXRay
 ID: 7B77:WQ2V:3WY6:QK6K:H5UL:BLGF:5THU:V5HA:DQY3:QLAV:NF72:HX2R
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false


```

### Logs

```
> Container logs (set LOG_LEVEL to debug if applicable) n/a
```

Switching the mariaDB container source to linuxserver solved this problem.

**Comment by crazy-max** [comment]
You can use `linuxserver/mariadb:10.5.13` or switch to an arm64 distrib like https://ubuntu.com/download/server/arm.
