### ISSUE TITLE
Weathermap environment not passing to container properly

### ISSUE THREAD

**Issue by smiles1969** [librenms/docker#251]
#### Steps to reproduce this issue

1. docker-compose librenms:librenms-latest
2. set LIBRENMS_WEATHERMAP=true in .env
3. docker-compose exec librenms env |grep WEATHERMAP

#### Expected behaviour

> Tell me what should happen
env for LIBRENMS_WEATHERMAP should be true inside container

#### Actual behaviour

> Tell me what happens instead
env for LIBRENMS_WEATHERMAP should be true inside container, but it is false no matter what

*** Can roll back to 21.12.1 tag release and behaves as expected

As a workaround, I have been running the map poller from a host OS cron

### Configuration

* Docker version (type `docker --version`) :
* Docker version 20.10.5+dfsg1, build 55c4c88
* Docker compose version if applicable (type `docker-compose --version`) :
*  Docker Compose version v2.2.2
* Platform (Debian 9, Ubuntu 18.04, ...) : 
* PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
* System info (type `uname -a`) : 
* Linux ctcv-docker 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

### Docker info

```
> Output of command `docker info`
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  scan: Docker Scan (Docker Inc., v0.12.0)

Server:
 Containers: 126
  Running: 29
  Paused: 0
  Stopped: 97
 Images: 138
 Server Version: 20.10.5+dfsg1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1.4.12~ds1-1~deb11u1
 runc version: 1.0.0~rc93+ds1-5+b2
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.0-10-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.63GiB
 Name: ctcv-docker
 ID: NTDO:MQSV:AR52:SA7S:CTWF:XXGF:5BIT:XGDR:6Q7D:IWVD:NWKM:C42H
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

### Logs

```
> Container logs (set LOG_LEVEL to debug if applicable)
```

**Comment by Jimmyord** [comment]
Work with Smiles last night, problem solve by deleting then pulling again librenms image.

**Comment by crazy-max** [comment]
> `set LIBRENMS_WEATHERMAP=true in .env`

`.env` is not used as env file in [our example](https://github.com/librenms/docker/blob/1fbca7d447a9e9bdf32d353d03e8541a40beab3c/examples/compose/docker-compose.yml#L61-L62)
