### ISSUE TITLE
Can't start using docker compose

### ISSUE THREAD

**Issue by resparis** [librenms/docker#259]
### Behaviour
I add a php file into /config but I dont see the changes

#### Steps to reproduce this issue

1. change the config from https://github.com/librenms/docker/blob/master/doc/notes/edit-config.md
- I enter to librenms dispatcher and I added a file called network_map_items.php
```
<?php
$config['network_map_items'] = array('xdp');
```
2. stop all services: "sudo docker-compose stop"
3. Start docker again: "sudo docker-compose up"

#### Expected behaviour

network_map_items [ "xdp" ]

#### Actual behaviour

network_map_items [ "xdp", "mac" ]

### Configuration

* Docker version (type `docker --version`) :
* Docker compose version if applicable (type `docker-compose --version`) : 
* Platform (Debian 9, Ubuntu 18.04, ...) : 
* System info (type `uname -a`) : 
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

### Docker info

```
Server:
 Containers: 25
  Running: 16
  Paused: 0
  Stopped: 9
 Images: 41
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.11.0-1022-aws
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.49GiB
 Name: ip-10-10-50-172
 ID: DQXG:TCRP:4EX2:CKGK:Z72A:RAMC:HDEE:E74V:KKWI:A5VS:UDSB:2XC5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

### Logs

```
> Container logs (set LOG_LEVEL to debug if applicable)
```

**Comment by crazy-max** [comment]
If you're still hitting this issue please post your compose stack, logs so we are able to repro. Thanks.
