### ISSUE TITLE
Adding snmptrapd to docker-compose and making it work?

### ISSUE THREAD

**Issue by coltonehrman** [librenms/docker#26]
How can I add SNMP trap handling to this docker compose config like this article is detailing https://docs.librenms.org/Extensions/SNMP-Trap-Handler/ ? I am not sure, but assuming this article is meant for non-docker installation/setups.

**Comment by crazy-max** [comment]
Adding a sidecar container like [syslog-ng](https://github.com/librenms/docker#syslog-ng) to this image should be a good start.

**Comment by crazy-max** [comment]
Fixed by #180

**Comment by hjcday** [comment]
@crazy-max Question, if I need to update the MIBs directory for my particular environment, at what level should I be doing this on my installation?

I have tried amending the 08-svc-snmptrapd.sh file to no luck and I have tried updating the snmptrapd/run file to no luck.

**Comment by hjcday** [comment]
Worked it out - PR created https://github.com/librenms/docker/pull/354
