### ISSUE TITLE
Cant access WebUI with Sidecar Dispatcher enabled

### ISSUE THREAD

**Issue by IWShady** [librenms/docker#263]
I dont know that its a bug or something with my particular setup. I have the LibreNMS, Redis, and rrdcached installed and all seem to be working together. However, I can only reach the WebUI if the Sidecar Dispatcher is disabled. I have the install behind an NGINX proxy server so perhaps I just need to adjust something. Any help would be greatly appreciated.

### Behaviour
When enabling the sidecar dispatcher the WebUI becomes unreachable. Both by direct IP and by name. The system appears to be working though as I can disable the sidecar and login and I see my one test device has graphed usage.

#### Steps to reproduce this issue

1. Spin up new LibreNMS install
2. Enable Sidecar Dispatcher
3. Try to load WebUI

#### Expected behaviour
WebUI should load with dispatcher enabled.

#### Actual behaviour
With sidecar enabled the WebUI is no longer accessible. Trying to connect by IP gives "Problem loading this page". By name it is behind an NGINX p-roxy server and it gives a 502 Bad Gateway.

### Configuration

* Docker version: Docker version 20.10.5, build 55c4c88
* Docker compose version if applicable: N/A, using unraid CA 
* Platform: Unraid 6.9.2
* System info: Linux deathstar 5.10.28-Unraid #1 SMP Wed Apr 7 08:23:18 PDT 2021 x86_64 Intel(R) Xeon(R) CPU E5-2630L 0 @ 2.00GHz GenuineIntel GNU/Linux 

### Docker info
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 32
  Running: 29
  Paused: 0
  Stopped: 3
 Images: 35
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.28-Unraid
 Operating System: Slackware 14.2 x86_64 (post 14.2 -current)
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 31.37GiB
 Name: deathstar
 ID: RF2V:7FPZ:DISL:RPT6:AG5Q:DFHN:37Q4:XK3D:6CMP:CNG4:WMZD:ONVY
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

### Logs
Thread-9(DEBUG):Posted work for poll to billing:0 queue size: 2
Alerting(DEBUG):Worker Alerting (0) got work alerts
Alerting(DEBUG):Queues: {'alerting:0': <LibreNMS.RedisUniqueQueue object at 0x14a50db48220>, 'alerting:3': <LibreNMS.RedisUniqueQueue object at 0x14a50db70b50>}
Alerting(INFO):Checking alerts
Alerting(DEBUG):Running ('/usr/bin/env', 'php', '/opt/librenms/alerts.php')
Thread-6(DEBUG):Posted work for alerts to alerting:0 queue size: 0
Thread-10(DEBUG):Posted work for to ping:3 queue size: 1
calculate_billing_timer(DEBUG):Posted work for calculate to billing:0 queue size: 2
Alerting(DEBUG):Command "('/usr/bin/env', 'php', '/opt/librenms/alerts.php')" returned with exit code "0". Command output was:
Alerting(DEBUG):Start: Wed, 04 May 2022 09:35:01 -0400
ClearStaleAlerts():
RunFollowUp():
RunAlerts():
RunAcks():
End : Wed, 04 May 2022 09:35:01 -0400

Alerting(INFO):Completed alerting run for alerts in 0.61s
Alerting(DEBUG):Worker Alerting checking queue 0 (0) for work
Poller_3-2(DEBUG):Worker Poller_3-2 checking queue 3 (0) for work
Poller_3-1(DEBUG):Worker Poller_3-1 checking queue 3 (0) for work
Poller_3-16(DEBUG):Worker Poller_3-16 checking queue 3 (0) for work
Poller_3-19(DEBUG):Worker Poller_3-19 checking queue 3 (0) for work
Poller_3-14(DEBUG):Worker Poller_3-14 checking queue 3 (0) for work
Poller_3-18(DEBUG):Worker Poller_3-18 checking queue 3 (0) for work
Poller_3-3(DEBUG):Worker Poller_3-3 checking queue 3 (0) for work
Poller_3-24(DEBUG):Worker Poller_3-24 checking queue 3 (0) for work
Poller_3-6(DEBUG):Worker Poller_3-6 checking queue 3 (0) for work
Poller_3-11(DEBUG):Worker Poller_3-11 checking queue 3 (0) for work
Discovery_3-3(DEBUG):Worker Discovery_3-3 checking queue 3 (0) for work
Poller_3-8(DEBUG):Worker Poller_3-8 checking queue 3 (0) for work
Poller_3-7(DEBUG):Worker Poller_3-7 checking queue 3 (0) for work
Poller_3-10(DEBUG):Worker Poller_3-10 checking queue 3 (0) for work
Poller_3-20(DEBUG):Worker Poller_3-20 checking queue 3 (0) for work
Poller_3-5(DEBUG):Worker Poller_3-5 checking queue 3 (0) for work
Poller_3-9(DEBUG):Worker Poller_3-9 checking queue 3 (0) for work
Poller_3-22(DEBUG):Worker Poller_3-22 checking queue 3 (0) for work
Poller_3-23(DEBUG):Worker Poller_3-23 checking queue 3 (0) for work
Poller_3-12(DEBUG):Worker Poller_3-12 checking queue 3 (0) for work
Poller_3-21(DEBUG):Worker Poller_3-21 checking queue 3 (0) for work
Poller_3-13(DEBUG):Worker Poller_3-13 checking queue 3 (0) for work
Poller_3-4(DEBUG):Worker Poller_3-4 checking queue 3 (0) for work
Poller_3-15(DEBUG):Worker Poller_3-15 checking queue 3 (0) for work
Poller_3-17(DEBUG):Worker Poller_3-17 checking queue 3 (0) for work
Discovery_3-13(DEBUG):Worker Discovery_3-13 checking queue 3 (0) for work
Discovery_3-16(DEBUG):Worker Discovery_3-16 checking queue 3 (0) for work
Discovery_3-9(DEBUG):Worker Discovery_3-9 checking queue 3 (0) for work
Discovery_3-5(DEBUG):Worker Discovery_3-5 checking queue 3 (0) for work
Discovery_3-4(DEBUG):Worker Discovery_3-4 checking queue 3 (0) for work
Discovery_3-2(DEBUG):Worker Discovery_3-2 checking queue 3 (0) for work
Discovery_3-8(DEBUG):Worker Discovery_3-8 checking queue 3 (0) for work
Discovery_3-10(DEBUG):Worker Discovery_3-10 checking queue 3 (0) for work
Discovery_3-12(DEBUG):Worker Discovery_3-12 checking queue 3 (0) for work
Services_3-5(DEBUG):Worker Services_3-5 checking queue 3 (0) for work
Discovery_3-6(DEBUG):Worker Discovery_3-6 checking queue 3 (0) for work
Services_3-7(DEBUG):Worker Services_3-7 checking queue 3 (0) for work
Discovery_3-1(DEBUG):Worker Discovery_3-1 checking queue 3 (0) for work
Discovery_3-11(DEBUG):Worker Discovery_3-11 checking queue 3 (0) for work
Services_3-6(DEBUG):Worker Services_3-6 checking queue 3 (0) for work
Services_3-1(DEBUG):Worker Services_3-1 checking queue 3 (0) for work
Discovery_3-15(DEBUG):Worker Discovery_3-15 checking queue 3 (0) for work
Discovery_3-7(DEBUG):Worker Discovery_3-7 checking queue 3 (0) for work
Services_3-2(DEBUG):Worker Services_3-2 checking queue 3 (0) for work
Discovery_3-14(DEBUG):Worker Discovery_3-14 checking queue 3 (0) for work
Services_3-4(DEBUG):Worker Services_3-4 checking queue 3 (0) for work
Services_3-3(DEBUG):Worker Services_3-3 checking queue 3 (0) for work
Services_3-8(DEBUG):Worker Services_3-8 checking queue 3 (0) for work
Alerting(DEBUG):Worker Alerting checking queue 0 (0) for work
Poller_3-2(DEBUG):Worker Poller_3-2 checking queue 3 (0) for work
Poller_3-1(DEBUG):Worker Poller_3-1 checking queue 3 (0) for work
Poller_3-12(DEBUG):Worker Poller_3-12 checking queue 3 (0) for work
Poller_3-18(DEBUG):Worker Poller_3-18 checking queue 3 (0) for work
Poller_3-7(DEBUG):Worker Poller_3-7 checking queue 3 (0) for work
Poller_3-5(DEBUG):Worker Poller_3-5 checking queue 3 (0) for work
Poller_3-23(DEBUG):Worker Poller_3-23 checking queue 3 (0) for work
Poller_3-22(DEBUG):Worker Poller_3-22 checking queue 3 (0) for work
Poller_3-16(DEBUG):Worker Poller_3-16 checking queue 3 (0) for work
Poller_3-15(DEBUG):Worker Poller_3-15 checking queue 3 (0) for work
Poller_3-11(DEBUG):Worker Poller_3-11 checking queue 3 (0) for work
Poller_3-4(DEBUG):Worker Poller_3-4 checking queue 3 (0) for work
Poller_3-10(DEBUG):Worker Poller_3-10 checking queue 3 (0) for work
Poller_3-24(DEBUG):Worker Poller_3-24 checking queue 3 (0) for work
Poller_3-3(DEBUG):Worker Poller_3-3 checking queue 3 (0) for work
Poller_3-17(DEBUG):Worker Poller_3-17 checking queue 3 (0) for work
Poller_3-8(DEBUG):Worker Poller_3-8 checking queue 3 (0) for work
Discovery_3-3(DEBUG):Worker Discovery_3-3 checking queue 3 (0) for work
Poller_3-6(DEBUG):Worker Poller_3-6 checking queue 3 (0) for work
Poller_3-21(DEBUG):Worker Poller_3-21 checking queue 3 (0) for work
Poller_3-13(DEBUG):Worker Poller_3-13 checking queue 3 (0) for work
Poller_3-9(DEBUG):Worker Poller_3-9 checking queue 3 (0) for work
Poller_3-14(DEBUG):Worker Poller_3-14 checking queue 3 (0) for work
Poller_3-20(DEBUG):Worker Poller_3-20 checking queue 3 (0) for work
Poller_3-19(DEBUG):Worker Poller_3-19 checking queue 3 (0) for work
Services_3-8(DEBUG):Worker Services_3-8 checking queue 3 (0) for work
Discovery_3-12(DEBUG):Worker Discovery_3-12 checking queue 3 (0) for work
Discovery_3-15(DEBUG):Worker Discovery_3-15 checking queue 3 (0) for work

**Comment by Gunsrude** [comment]
I had this issue when I was setting up shared environment variables. 
It was because SIDECAR_DISPATCHER and DISPATCHER_NODE_ID were defined on both containers for me.

**Comment by murrant** [comment]
SIDECAR_DISPATCHER does not run a web server (or other services) it only runs the dispatcher.
