### ISSUE TITLE
Does syslog_hook work in dockerized LibreNMS?

### ISSUE THREAD

**Issue by gitcatpeter** [librenms/docker#273]
I have a problem triggering any action via syslog_hook when a desired syslog event is received. Has anybody tested it using docker LibreNMS installation?

The whole stack is using compose file from this site (LibreNMS is v 22.4.0).
I have a syslog-ng container configured as **"SIDECAR_SYSLOGNG=1"** as well as one dispatcher.
Syslog events properly populate in LibreNMS, yet no event is triggered.
I deliberately set the hook as in the below output to prove, that even the first step is never executed (namely script under os.ironware.syslog_hook)

The following required values were set in **data/config** via a custom php file and the values are properly set and readable from within librenms/dispatcher/syslog-ng containers:

```
lnms config:get enable_syslog
1
lnms config:get enable_syslog_hooks
1
lnms config:get os.ironware.syslog_hook  //deliberately set like this to troubleshoot, the script just executes **touch** command)
[
    {
        "regex": "/startup-config was changed by/",
        "script": "/tmp/a.php"
    }
]

ls -al /tmp/a.php 
-rwxr-xr-x 1 librenms librenms 44 May 23 22:34 /tmp/a.php

```
The device itself presents as below:
```
curl -H 'X-Auth-Token: xxx' http://xxxyyy:8222/api/v0/oxidized
[
    {
        "hostname": "icx6610-01.xxx.xxx",
        "os": "ironware",
        "ip": "192.168.0.10",
        "group": "icx6610"
    }
```

and the syslog message to trigger:
```
2022-05-23T23:13:01.537Z ICX6610-01 - - - [meta sequenceId=1577] BOMSecurity: startup-config was changed by root from ssh client 192.168.0.210
```

-time is in sync within each container

I do not see any logs relevant to the issue. Please help troubleshoot the issue or a bug.

**Comment by murrant** [comment]
The problem is your file location.   /tmp access is privitized on linux.

**Comment by murrant** [comment]
You should store the script in your shared data partition, so it doesn't matter.

Script should be run from syslog.php entry which is ran by the syslog daemon.  So should be in the syslog sidecar.

**Comment by gitcatpeter** [comment]
Following your advice I was able to execute a custom php script when certain syslog msg was received.
I placed a custom syslog-notify-oxidized.php on a shared data partition and referenced it in the syslog_hook.
I know that the custom syslog-notify-oxidized.php script gets executed (again using touch commang in it), but the vital part never executes.
Unfortunatelly I'm not familiar with PHP, but I placed the following:
```
var_dump($hostname);
var_dump($os);
var_dump ($msg);
```

past this block
```
$hostname = $argv[1];
$os = $argv[2];
$msg = $argv[3];
```


and they all return **NULL**.
Seems in my case arguments are not passed to the script and it can't evaluate the condition.
Not sure where it should get these arguments appended.

The hook is 
$config['os']['ironware']['syslog_hook'][] = Array('regex' => '/startup-config was changed by/', 'script' => '/data/custom/_custom_syslog-notify-oxidized.php');

**Comment by gitcatpeter** [comment]
It works when I specify the arguments explicitly, but I guess it's not the intended behavior:
`$config['os']['ironware']['syslog_hook'][] = Array('regex' => '/startup-config was changed by/', 'script' => '/data/custom/_custom_syslog-notify-oxidized.php icx6610-01.xxx.yyy ironware "startup-config was changed by"');`

and the syslog notify script and var_dumps returns arguments as expected:
```
string(21) "icx6610-01.xxx.yyy"
string(8) "ironware"
string(29) "startup-config was changed by"
```

**Comment by gitcatpeter** [comment]
No comments?
Is it a LNMS bug in Docker environment?

**Comment by murrant** [comment]
You sure you are sending the logs correctly?

**Comment by gitcatpeter** [comment]
If you can be more specific I'm willing to either make a fool of myself or trace a real issue ;-)
Please provide exactly what I have to do/take logs.
Thank you.

**Comment by murrant** [comment]
Probably the best thing you could do is a regular install of LibreNMS and duplicate the syslogs to it to verify.  I suspect this is either a configuration issue, or bug/deficiency in LibreNMS.  Unlikely to have anything to do with the docker.

**Comment by gitcatpeter** [comment]
Sorry, no time to stand up a VM and repeat the whole install and config.
But willing to debug the existing issue.
Refering to my previous observations:
1. In LNMS documentation the hook (script) is called without command-line arguments:
`$config['os']['ironware']['syslog_hook'][] = Array('regex' => '/startup-config was changed by/', 'script' => '/data/custom/_custom_syslog-notify-oxidized.php');`
and I've proven the hook is executed, but does nothing because no arguments are passed to it (argv[1]..[3]). Hence the condition is never true.
So when I define the same hook with explicit arguments
`$config['os']['ironware']['syslog_hook'][] = Array('regex' => '/startup-config was changed by/', 'script' => '/data/custom/_custom_syslog-notify-oxidized.php icx6610-01.xxx.yyy ironware "startup-config was changed by"');`
it works as the arguments are present within the hook's code.
No idea how the hook should get those arguments in the 1st case (global variables?), but it does not have them.

I think that's pretty clear indication of where the problem could be. I just assume that since functionality is split between containers, something is not passed from one instance to another.

**Comment by murrant** [comment]
https://github.com/librenms/librenms/blob/master/includes/syslog.php#L69

Still doesn't make any sense.  If the script is called, then $os has to be populated because that is needed to look up the hook and $msg is always at minimum ':'

Because the syslog daemon calls syslog.php, it all happens under the syslog daemon parent process.  It isn't doing anything in different containers.

Additionally, I've submitted a change that might help you a bit: https://github.com/librenms/librenms/pull/14011  No need to duplicate the script to do the same thing.
