### ISSUE TITLE
Weathermap is not saving maps in docker installation

### ISSUE THREAD

**Issue by mad-max-traveller** [librenms/docker#294]
Hello.
I have:
====================================
Component | Version
--------- | -------
LibreNMS  | 22.6.0
DB Schema | 2022_05_30_084932_update-app-status-length (242)
PHP       | 7.4.30
Python    | 3.9.7
MySQL     | 10.5.16-MariaDB-1:10.5.16+maria~focal
RRDTool   | 1.7.2
SNMP      | 5.9.1
====================================

[OK]    Installed from package; no Composer required
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[WARN]  IPv6 is disabled on your server, you will not be able to add IPv6 devices.
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
[WARN]  Non-git install, updates are manual or from package

Installed in accordance with the instructions.
I have created a map and can't find it anywhere.
In the logs I saw the following:

`librenms | PHP Notice: fgets(): read of 8192 bytes failed with errno=21 Is a directory in /opt/librenms/html/plugins/Weathermap/lib/Weathermap.class.php on line 1817
librenms | PHP Notice: file_get_contents(): read of 8192 bytes failed with errno=21 Is a directory in /opt/librenms/html/plugins/Weathermap/lib/Weathermap.class.php
on line 3259
librenms | PHP Warning: imagepng(weathermap.png): failed to open stream: Permission denied in /opt/librenms/html/plugins/Weathermap/lib/Weathermap.class.php on line
3494
librenms | WARNING: configs//weathermap: Failed to create image file weathermap.png - permissions of output directory are wrong? [WMWARN14]
librenms | PHP Warning: imagecreatefrompng(): gd-png: libpng warning: iCCP: known incorrect sRGB profile in /opt/librenms/html/plugins/Weathermap/lib/WeatherMap.func
tions.php on line 401
librenms | PHP Warning: imagepng(narodnaya29.png): failed to open stream: Permission denied in /opt/librenms/html/plugins/Weathermap/lib/Weathermap.class.php on line
3494
librenms | WARNING: configs//narodnaya-29.conf: Failed to create image file narodnaya29.png - permissions of output directory are wrong? [WMWARN14]
librenms | PHP Warning: fopen(narodnaya29.html): failed to open stream: Permission denied in /opt/librenms/html/plugins/Weathermap/weathermap.php on line 304
librenms | PHP Warning: fwrite() expects parameter 1 to be resource, bool given in /opt/librenms/html/plugins/Weathermap/weathermap.php on line 306
librenms | PHP Warning: fwrite() expects parameter 1 to be resource, bool given in /opt/librenms/html/plugins/Weathermap/weathermap.php on line 307
librenms | PHP Warning: fwrite() expects parameter 1 to be resource, bool given in /opt/librenms/html/plugins/Weathermap/weathermap.php on line 309
librenms | PHP Warning: fwrite() expects parameter 1 to be resource, bool given in /opt/librenms/html/plugins/Weathermap/weathermap.php on line 314
librenms | PHP Warning: fwrite() expects parameter 1 to be resource, bool given in /opt/librenms/html/plugins/Weathermap/weathermap.php on line 316
librenms | PHP Warning: fwrite() expects parameter 1 to be resource, bool given in /opt/librenms/html/plugins/Weathermap/weathermap.php on line 319
librenms | PHP Warning: fwrite() expects parameter 1 to be resource, bool given in /opt/librenms/html/plugins/Weathermap/weathermap.php on line 323
librenms | PHP Warning: fclose() expects parameter 1 to be resource, bool given in /opt/librenms/html/plugins/Weathermap/weathermap.php on line 324`

**Comment by murrant** [comment]
In your data directory, is /data/weathermap owned by the UID:GID you specified for the LibreNMS user?

**Comment by mad-max-traveller** [comment]
Yes.
root@lserver01:/mnt/data/librenms# ls -l
total 0
drwxr-xr-x 1 systemd-coredump systemd-coredump 274 июл 15 11:17 db
drwxr-xr-x 1 user          user          152 июл 15 10:10 librenms

root@lserver01:/mnt/data/librenms# id user
uid=1000(user) gid=1000(user) 
groups=1000(user),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),116(lxd)

root@lserver01:/mnt/data/librenms/librenms# ls -l
total 0
drwxr-xr-x 1 user user    0 июл 15 10:10 alert-templates
drwxr-xr-x 1 user user   20 июл 15 11:13 config
drwxrwxr-x 1 user user   42 июл 16 00:15 logs
drwxr-xr-x 1 user user    0 июл 15 10:10 monitoring-plugins
drwxr-xr-x 1 user user    0 июл 15 10:10 plugins
drwxrwxr-x 1 user user 2370 июл 18 14:22 rrd
drwxr-xr-x 1 user user    0 июл 15 10:10 syslog-ng
drwxr-xr-x 1 user user   54 июл 15 11:44 weathermap

My .env:
TZ= # my_tz

PUID=1000
PGID=1000

MYSQL_DATABASE=librenms
MYSQL_USER=librenms
MYSQL_PASSWORD= # my_pass

The .conf file is created, I can see it. Could it be a permissions problem inside the image?

librenms:/opt/librenms/html/plugins/Weathermap$ ls -l
total 276
-rwxr-xr-x 1 nobody   nogroup  38807 Jul 14 19:12 CHANGES
-rw-r--r-- 1 nobody   nogroup  18011 Jul 14 19:12 COPYING
-rw-r--r-- 1 nobody   nogroup   2038 Jul 14 19:12 INSTALL.md
-rw-r--r-- 1 nobody   nogroup   1091 Jul 14 19:12 LICENSE
-rw-r--r-- 1 nobody   nogroup   1975 Jul 14 19:12 README.md
-rw-r--r-- 1 nobody   nogroup  18811 Jul 14 19:12 TODO
-rw-r--r-- 1 nobody   nogroup   1882 Jul 14 19:12 TODO-for-0.98.md
-rw-r--r-- 1 nobody   nogroup   1309 Jul 14 19:12 Weathermap.inc.php
-rw-r--r-- 1 nobody   nogroup   1143 Jul 14 19:12 Weathermap.php
-rw-r--r-- 1 nobody   nogroup   1631 Jul 14 19:12 check-gdbug.php
-rwxr-xr-x 1 nobody   nogroup  12829 Jul 14 19:12 check.php
-rw-r--r-- 1 nobody   nogroup    734 Jul 14 19:12 config.inc.php
lrwxrwxrwx 1 root     root        16 Jul 15 10:10 configs -> /data/weathermap
-rwxr-xr-x 1 nobody   nogroup  14883 Jul 14 19:12 data-pick.php
-rw-r--r-- 1 nobody   nogroup    940 Jul 14 19:12 defaults.inc.php
drwxr-xr-x 1 nobody   nogroup    148 Jul 14 19:12 docs
drwxr-xr-x 1 nobody   nogroup     18 Jul 14 19:12 editcache
drwxr-xr-x 1 nobody   nogroup   3828 Jul 14 19:12 editor-resources
-rwxr-xr-x 1 nobody   nogroup  51131 Jul 14 19:12 editor.php
drwxr-xr-x 1 nobody   nogroup   3320 Jul 14 19:12 images
-rw-r--r-- 1 nobody   nogroup     59 Jul 14 19:12 index.php
drwxr-xr-x 1 nobody   nogroup    612 Jul 14 19:12 lib
-rwxr-xr-x 1 nobody   nogroup   2174 Jul 14 19:12 map-poller.php
drwxr-xr-x 1 librenms librenms    18 Jul 14 19:12 output
-rw-r--r-- 1 nobody   nogroup  49243 Jul 14 19:12 overlib.js
drwxr-xr-x 1 nobody   nogroup    638 Jul 14 19:12 random-bits
drwxr-xr-x 1 nobody   nogroup    104 Jul 14 19:12 vendor
-rwxr-xr-x 1 nobody   nogroup  10080 Jul 14 19:12 weathermap.php
librenms:/opt/librenms/html/plugins/Weathermap$ cd configs/

librenms:/data/weathermap$ ls -l
total 8
-rw-r--r-- 1 librenms librenms 1296 Jul 18 14:34 narodnaya-29.conf
lrwxrwxrwx 1 root     root       16 Jul 15 11:17 weathermap -> /data/weathermap

**Comment by murrant** [comment]
It is trying to write to narodnaya29.html in the output directory.  I wonder why it is failing.  Do you have read-only rootfs enabled?

Probably, the output directory needs to be set to a tmpfs directory, if that is the case.

**Comment by crazy-max** [comment]
`weathermap -> /data/weathermap` looks odd, I will try to repro.

**Comment by mad-max-traveller** [comment]
> It is trying to write to narodnaya29.html in the output directory. I wonder why it is failing. Do you have read-only rootfs enabled?

It's a Docker image. I don't do any manipulation with it. Maybe I don't understand your question?

**Comment by mad-max-traveller** [comment]
I upgraded today.
```
$ docker-compose pull
$ docker-compose up
```

LibreNMS stopped working, I keep seeing the same error in the console:
```
dispatcher_1  | 'NoneType' object has no attribute 'get'
dispatcher_1  | MainThread(CRITICAL):ERROR: Could not execute command [['/usr/bin/env', 'php', '/opt/librenms/config_to_json.php']]: Expecting value: line 2 column 1 (char 1)
dispatcher_1  | 'NoneType' object has no attribute 'get'
librenms      | [s6-finish] sending all processes the KILL signal and exiting.
dispatcher_1  | MainThread(CRITICAL):ERROR: Could not execute command [['/usr/bin/env', 'php', '/opt/librenms/config_to_json.php']]: Expecting value: line 2 column 1 (char 1)
dispatcher_1  | 'NoneType' object has no attribute 'get'
librenms exited with code 1
```
