### ISSUE TITLE
Weathermap plugin breaks LibreNMS 22.7.0

### ISSUE THREAD

**Issue by marcogiorgio** [librenms/docker#296]
#### Steps to reproduce this issue

1. Update LibreNMS to 22.7.0
2. Launch Web UI

#### Expected behaviour

> WebUI gets to login page

#### Actual behaviour

> Whoops, something went wrong, Check your librenms.log

### Configuration

* Docker version : 20.10.17
* Docker compose version: 2.6.0
* Platform: Ubuntu 22.04 
* System info: Linux srvmonitor 5.15.0-41-generic 44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Hi,
today I upgraded LibreNMS to the latest version (22.7.0) using docker compose, but after the update, the homepage says: "Whoops, something went wrong, Check your librenms.log". I reverted back to 22.6.0 and LibreNMS started working normally. Has anyone encountered the same problem?

Error log:

[2022-07-25T16:00:45.775948+02:00] production.ERROR: ksort(): Argument 1 ($array) must be of type array, null given (View: /opt/librenms/resources/views/layouts/librenmsv1.blade.p
[previous exception] [object] (Illuminate\\View\\ViewException(code: 0): ksort(): Argument 1 ($array) must be of type array, null given (View: /opt/librenms/resources/views/layout
[previous exception] [object] (TypeError(code: 0): ksort(): Argument 1 ($array) must be of type array, null given at /opt/librenms/html/plugins/Weathermap/lib/editor.inc.php:168)"

**Comment by marcogiorgio** [comment]
The issue has been reported here by another user: [https://community.librenms.org/t/production-error-ksort-argument-1-array-must-be-of-type-array/19236/2](). Probably it's a general LibreNMS issue, in that case feel free to close this post. Thanks

**Comment by murrant** [comment]
Weathermap does (not LibreNMS) seems to have an issue on PHP 8.  Will need to get it fixed there: https://github.com/librenms-plugins/Weathermap

**Comment by marcogiorgio** [comment]
Thanks for your reply. In fact I tried to set ENABLE_WEATHERMAP=false, but it wasn't enough. I'll wait for a fix.
Thanks

**Comment by Laplacence** [comment]
at 22.6.0
disable the weathermap plugin,
then it work fine at 22.7.0 :D

**Comment by marcogiorgio** [comment]
> at 22.6.0 disable the weathermap plugin, then it work fine at 22.7.0 :D

Disabling the plugin in WebUI did the trick. Thanks for the workaround

**Comment by ryanmerolle** [comment]
interesting weathermap is already disabled in the UI for me, but still is causing issues when I switch to 22.7.0

**Comment by mkidle** [comment]
This issue is encountered only if there are NO configuration files in the weathermap configs directory. Even an empty file works fine. This gives you GUI access to disable the plugin, as you are obviously not using it. Users that already are using Weathermap are naturally not affected by this bug. 

Example workaround in shell:
sudo su - librenms
touch  /opt/librenms/html/plugins/Weathermap/configs/dummy.conf
exit

**Comment by crazy-max** [comment]
@murrant https://github.com/librenms-plugins/Weathermap/pull/79 might fix issue with Weathermap and PHP 8 so we could bring it back in the Docker image.
