### ISSUE TITLE
On alert, dispatcher service is unable to send alerts via transport despite transport tests working correctly.

### ISSUE THREAD

**Issue by Aterfax** [librenms/docker#297]
#### Steps to reproduce this issue

1. Use the example docker compose.
2. Set up and test a working transport then add a device and alert rule that will trigger. (Toggling acknowledgement should also send an alert via your transport and will be easier for testing than fiddling with alert rules to fire.)
3. Set the dispatcher logging to debug and observe logs

#### Expected behaviour

Triggered alerts should send via transports. 

#### Actual behaviour

Triggered alerts do not send via transports. 

### Configuration

* Docker version (type `docker --version`) : `Docker version 20.10.16, build aa7e414`
* Docker compose version if applicable (type `docker-compose --version`) : `Docker Compose version v2.5.0`
* Platform (Debian 9, Ubuntu 18.04, ...) : `Ubuntu 22.04 LTS`
* System info (type `uname -a`) :  `Linux librenms 5.15.0-41-generic #44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

Not adding these (yet) as I do not believe these are actually related to the cause. I can add these on request. 

### Docker info

``` bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  compose: Docker Compose (Docker Inc., v2.5.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 11
  Running: 11
  Paused: 0
  Stopped: 0
 Images: 9
 Server Version: 20.10.16
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc version: v1.1.1-0-g52de29d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-41-generic
 Operating System: Ubuntu 22.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.634GiB
 Name: librenms
 ID: BRHN:N4S5:MVDW:LNTX:JBAW:VH7Q:64QB:BLDP:R4D6:37Y5:2X6H:HVST
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

### Logs

Specific relevant excerpt:
```bash
 Alerting(DEBUG):Command "('/usr/bin/env', 'php', '/opt/librenms/alerts.php')" returned with exit code "0". Command output was:
librenms_dispatcher  | Alerting(DEBUG):
librenms_dispatcher  | In Factory.php line 90:
librenms_dispatcher  |
librenms_dispatcher  |   Unknown connection scheme: ''.
librenms_dispatcher  |
librenms_dispatcher  |
librenms_dispatcher  |
```

Log appears to refer to ``/opt/librenms/vendor/predis/predis/src/Connection/Factory.php``

Which contains

```php
    public function create($parameters)
    {
        if (!$parameters instanceof ParametersInterface) {
            $parameters = $this->createParameters($parameters);
        }

        $scheme = $parameters->scheme;

        if (!isset($this->schemes[$scheme])) {
            throw new \InvalidArgumentException("Unknown connection scheme: '$scheme'.");
        }

        $initializer = $this->schemes[$scheme];
```

Which suggests that a scheme e.g. TLS not being present is causing a problem.

See: 

- https://laravel.com/docs/9.x/redis#configuring-the-connection-scheme
- https://bestofphp.com/repo/predis-predis-php-nosql

I guess this might be fixed by setting the scheme to ``tcp`` by adding a new environment variable from which this can be set via the Docker variables. Probably best to set alongside:

```
CACHE_DRIVER=redis
SESSION_DRIVER=redis
REDIS_HOST=redis
```

Inside of: ``librenms.env``

as:

```
CACHE_DRIVER=redis
SESSION_DRIVER=redis
REDIS_HOST=redis
REDIS_SCHEME=tcp
```

**Comment by Aterfax** [comment]
Tested this as a fix which appears to work.

**Comment by sefirosweb** [comment]
I have spent almost 4 hours to find this post,

finally solved, thanks
