### ISSUE TITLE
Document configuration necessary for basic setup

### ISSUE THREAD

**Issue by kylegentle** [librenms/docker#30]
Describing the minimum necessary configuration to run a "vanilla" LibreNMS would improve the usability of this repo, and make it more accessible to newcomers.

Docker Compose is recommended under the **Use this image** section of the README, and the section mentions editing the example compose and env files. However it doesn't specify what needs to be changed and what is safe to leave as default.

For someone like myself who is brand new to LibreNMS but has some experience with Docker and Docker Compose, what's the quickest way to get up and running?

**Comment by crazy-max** [comment]
In docker-compose file example :

* Replace `webmaster@example.com` (ACME).
* Replace `librenms.example.com`.
* Replace `example.com`.
* You can omit the syslog-ng service if you do not intend to use it.

In the .env file, replace with your preferences. (don't need to say change db password)

And librenms.env it's fine by default.
