### ISSUE TITLE
librenms container restarting continously with 22.7.0-r1

### ISSUE THREAD

**Issue by lemppari** [librenms/docker#303]
After updating to release 22.7.0-r1 librenms container is restarting itself.

#### Steps to reproduce this issue

I was running 22.7.0-r0 couple of weeks without any issues. I updated to 22.7.0-r1 yesterday and noticed that ibrenms container keeps restarting.

After altering my docker-compose.yml to use image:
image: librenms/librenms:22.6.0

I got my installation running again. I've attached my docker-compose.yml and a snippet from output of docker-compose logs -f

### Configuration

* Docker version (type `docker --version`) : Docker version 20.10.17, build 100c701
* Docker compose version if applicable (type `docker-compose --version`) :  docker-compose version 1.29.1, build c34c88b2
* Platform (Debian 9, Ubuntu 18.04, ...) : Debian 11.4
 
* System info (type `uname -a`) : Linux fricka 5.10.0-16-amd64  SMP Debian 5.10.127-2 (2022-07-23) x86_64 GNU/Linux
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...
* 
[log snippet.txt](https://github.com/librenms/docker/files/9333196/log.snippet.txt)
[docker-compose.yml.txt](https://github.com/librenms/docker/files/9333200/docker-compose.yml.txt)

**Comment by crazy-max** [comment]
I guess it happens on restart with `docker compose restart`. But good catch though, will fix that.

**Comment by lemppari** [comment]
Fix confirmed, back to normal operation with 22.7.0-r2. Thanks!
