### ISSUE TITLE
Alert Transporting not working when running on a  poller.

### ISSUE THREAD

**Issue by LoveSkylark** [librenms/docker#305]
### Behaviour

No alerts are being transmitted with "Alert Transport"  when you run librenms/docker
Alerts get created just fine and the Poller log has no errors.

#### Steps to reproduce this issue
Libre WebUI > transport test button => message sent
Libre CLI > test-alert.psp => message sent
Libre CLI > alerts.php  => message sent
Poller CLI > alerts.php  => "In Factory.php line 90:   Unknown connection scheme: ''

/data/alert-templates/ is empty on both containers and there is no folder for transport, so I suspect volume mapping needs to be fixed so the poller can read the dad from librenms. (or alerts.php need to be run at librenms?)

**Comment by murrant** [comment]
Can you get the full backtrace from alerts.php?

**Comment by LoveSkylark** [comment]
this?

/opt/librenms $ ./alerts.php -d
DEBUG!
Unknown connection scheme: ''. {"exception":"[object] (InvalidArgumentException(code: 0): Unknown connection scheme: ''. at /opt/librenms/vendor/predis/predis/src/Connection/Factory.php:90)"} 

In Factory.php line 90:
                                  
  Unknown connection scheme: ''.

**Comment by LoveSkylark** [comment]
This has ben resolved with adding "REDIS_SCHEME=tcp" to the config file

**Comment by murrant** [comment]
REDIS_SCHEME should already be set to tcp by default and default to tcp if not set.  I wonder what is going on here?

**Comment by murrant** [comment]
Defaulting to '' breaks this logic `'scheme' => env('REDIS_SCHEME', 'tcp'),`  The docker should either not set REDIS_SCHEME by default or set it to tcp

**Comment by murrant** [comment]
Should be fixed by #300
