### ISSUE TITLE
Default password for docker install?

### ISSUE THREAD

**Issue by Yonny24** [librenms/docker#321]
I have followed the instructions from https://docs.librenms.org/Installation/Docker/

I can access the login page from a browser but cannot find the dafault login and password anywhere. Tried many options
librenms/librenms was my first attempt. then my root/password etc.

Please can you let me know what this script sets as the DB_PASSWORD? 

Thanks

**Comment by murrant** [comment]
You create the login when you first open the web page as described in the docs.

https://github.com/librenms/docker#first-launch
