### ISSUE TITLE
Suggestion: set project name to "librenms" in docker-compose.yml

### ISSUE THREAD

**Issue by candlerb** [librenms/docker#325]
#### Steps to reproduce this issue

1. `cd examples/compose`
2. `docker compose up -d`

#### Expected behaviour

The docker-compose project to be called "librenms"

#### Actual behaviour

The created project is called "compose" (see `docker compose ls`), and so are other resources which are named from it, such as the network:

```
$ docker network list
NETWORK ID     NAME                    DRIVER    SCOPE
...
bae06792b684   compose_default         bridge    local
```

This is because the project name defaults to the name of the enclosing directory, which indeed in this case is "compose".

However this is easily fixed by adding a top-level "name" setting to docker-compose.yml, i.e.

```
version: "3.5"
name: librenms     # <<<< ADD THIS

services:
   ... etc
```

(Aside: it can still be overridden by `docker compose up -p <projectname>`, in case you want to run multiple instances of the librenms stack concurrently)

### Configuration

* Docker version (type `docker --version`) : 5:20.10.21~3-0~ubuntu-jammy
* Docker compose version if applicable (type `docker-compose --version`) : docker-compose-plugin 2.12.2~ubuntu-jammy
* Platform (Debian 9, Ubuntu 18.04, ...) : Ubuntu 22.04.1
* System info (type `uname -a`) : `Linux noc 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...: see above

**Comment by murrant** [comment]
sounds reasonable, I suggest sending a change request for the same.
