### ISSUE TITLE
unable to docker-compose up -d

### ISSUE THREAD

**Issue by jeevadotnet** [librenms/docker#33]
#### Steps to reproduce this issue

1. copy the 3 example files from to /var/librenms as per the docker guide
2. setup smtp & mysql db password, also change docker-compose.yml version to 2.0
3. run `docker-compose up-d`

#### Expected behaviour

> Docker to compose and have a running container

#### Actual behaviour

```:/var/librenms$ sudo docker-compose up -d
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.traefik.ports is invalid: Invalid port "{'protocol': 'tcp', 'target': 443, 'published': 443}", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.traefik.ports contains an invalid type, it should be a string, or a number
services.syslog-ng.ports is invalid: Invalid port "{'protocol': 'tcp', 'target': 514, 'published': 514}", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.syslog-ng.ports contains an invalid type, it should be a string, or a number
services.traefik.ports is invalid: Invalid port "{'protocol': 'tcp', 'target': 80, 'published': 80}", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.traefik.ports contains an invalid type, it should be a string, or a number
services.syslog-ng.ports is invalid: Invalid port "{'protocol': 'udp', 'target': 514, 'published': 514}", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.syslog-ng.ports contains an invalid type, it should be a string, or a number
```

### Configuration

* Docker version (type `docker --version`) : `Docker version 18.09.2, build 6247962`
* Docker compose version if applicable (type `docker-compose --version`) : `docker-compose version 1.8.0, build unknown`
* Platform (Debian 9, Ubuntu 18.04, ...) : `Ubuntu 16.04 LTS`
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

**Comment by crazy-max** [comment]
As your log said your compose file is invalid because you are using an older version (2.0). Stick to our [compose file version](https://github.com/librenms/docker/blob/master/examples/compose/docker-compose.yml#L1) or make the necessary changes.
