### ISSUE TITLE
service 'name' must be a mapping not a string

### ISSUE THREAD

**Issue by dewiweb** [librenms/docker#330]
### Behaviour
Can't launch librenms-docker on centos7 with docker-compose.yml
#### Steps to reproduce this issue

1.  sudo docker-compose up
2.
3.

#### Expected behaviour
ERROR: In file './docker-compose.yml', service 'name' must be a mapping not a string.
> Tell me what should happen

#### Actual behaviour

> Tell me what happens instead

### Configuration

* Docker version (type `docker --version`) : Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:05:12 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:03:33 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
* Docker compose version if applicable (type `docker-compose --version`) :  latest
* Platform (Debian 9, Ubuntu 18.04, ...) : centos7
* System info (type `uname -a`) : Linux gateway.regieconf.lan 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

### Docker info

```
> Output of command `docker info`
```

### Logs

```
> Container logs (set LOG_LEVEL to debug if applicable)
```

**Comment by seaplusplus** [comment]
https://github.com/librenms/docker/commit/453b31cc641a5ebb4984fe976ca6ef3b1d133c36 

This commit breaks it.  Change name to version gets it working again.

**Comment by joshbuker** [comment]
I noticed that `docker compose up -d` will work with the name, while `docker-compose up -d` does not. Not sure if this is because `docker compose` is more lenient in what it accepts in the compose file, but it's probably related.

**Comment by EpicLPer** [comment]
From what I just read there's a "docker-compose" and "docker compose", one is a standalone thing while the other is a plugin for the actual Docker CLI.  
v1 doesn't come (?) with the "compose" option, but v2 does. Upgrading my installation right now to test this out.

**Comment by EpicLPer** [comment]
Yep, that seems to have been the solution. "docker compose version" now works too, so an upgrade of the packages seems to be the solution.

As a PSA, v1 seems to go out of support in June 2023, so an upgrade is probably good anyways :)

**Comment by crazy-max** [comment]
`docker-compose` v1 is EOL, please update to v2
