### ISSUE TITLE
Add Custom Devices through container

### ISSUE THREAD

**Issue by tweak19** [librenms/docker#337]
Hi,
Not a typical issue but maybe here at the right place.
I search for a way to add custom MIB Files and Custom yaml files (for devices) to the container. I currently run my lbrenms instanz native but with the issue that on every update my files are lost. 

Second part why switch to docker is necessary is the required php version. 

May anybody can help out here.
Thx!

**Comment by tweak19** [comment]
No Feedback? Or any Idea how to do this? 
Isn't it possible to map an folder to this point?

**Comment by murrant** [comment]
Honestly, for now,  the easiest option is to contribute upstream. Or inject the files after every image update.
