### ISSUE TITLE
ipmitool location does not exist

### ISSUE THREAD

**Issue by kylegordon** [librenms/docker#34]
### Behaviour

IPMI does not work out of the box with Docker versions of LibreNMS

#### Steps to reproduce this issue

1. Fresh Docker container
2. docker exec -it librenms /bin/bash
3. Configure a host in LibreNMS with appropriate IPMI hostname and credentials
3. ./poller.php -h yourhost -m ipmi

#### Expected behaviour

ipmitool is found and used

#### Actual behaviour

Logs will scroll past, and briefly it will complain about being unable to locate /usr/sbin/ipmitool. No IPMI data will be discovered

### Configuration

* Docker version (type `docker --version`) : 18.09.6, build 481bc77
* Docker compose version if applicable (type `docker-compose --version`) : 1.24.0, build 0aa59064
* Platform (Debian 9, Ubuntu 18.04, ...) : Ubuntu 18.04.2 LTS

It would appear that the default is to use /usr/bin/ipmitool, yet the binary exists in /usr/sbin/ipmitool. The install can be tweaked by including 

```
<?php
$config['ipmitool'] = "/usr/sbin/ipmitool";
```
in data/config/ipmitool.php, but it might be nice to include this by default somehow.

**Comment by crazy-max** [comment]
Should be fixed now, thanks for your input.
