### ISSUE TITLE
Unable to persistant "device_display_default"

### ISSUE THREAD

**Issue by tweak19** [librenms/docker#344]
#### Steps to reproduce this issue

1. Go to Global-Settings -> Web UI -> Device Settings -> Switch "Default device display name template" from "Hostname / IP" to "Hostname, fallback to SysName for IPs" 
2. wait 1h
3. Setting revented

#### Expected behaviour

> Keep this setting persistent

#### Actual behaviour

> look at Steps to reproduce

**Comment by murrant** [comment]
Delete force_hostname_to_sysname and force_ip_to_sysname from your config.php
