### ISSUE TITLE
external ip required but not documented

### ISSUE THREAD

**Issue by ckozler** [librenms/docker#35]
### Behaviour

It is not documented that you need an externally resolvable DNS name for ACME to work correctly and in addition to this, the IP that resolves must be reachable from the outside in

If this can be changed in some way, easily, please let me know and I will submit a pull request

#### Steps to reproduce this issue

1. Follow instructions
2. Set some random hostname for hostname settings
3. Make sure domain matches what you set in #2 (for continuity)
4. docker-compose up -d 
5. Navigate to your hostname
6. 404 error

First error was NXDOMAIN even though I could resolve it while on the container. Realized then it was ACME web service spitting out the NXDOMAIN

Second was adding the domain name to be resolvable outside but then ACME didnt like that I was using an internal IP 

Third was opening firewall rules and creating a NAT just for this

An internal IP should at least be reasonable. It shouldnt involve this many separate external units to get working additionally no documentation to support. I needed to make updates to firewall, NAT's, and DNS to make this work 

#### Expected behaviour

> Tell me what should happen

Librenms should load, regardless if ACME was able to generate a cert or not

#### Actual behaviour

> Tell me what happens instead

404 page not found with ACME errors in traefik logs

### Configuration

* Docker version (type `docker --version`) :
* Docker compose version if applicable (type `docker-compose --version`) : 
* Platform (Debian 9, Ubuntu 18.04, ...) : 
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

### Docker info

```
> Output of command `docker info`
```

### Logs

```
> time="2019-08-13T22:50:11Z" level=info msg="legolog: [INFO] Unable to deactivate the authorization: https://acme-v02.api.letsencrypt.org/acme/authz/VucPmcgT3SNA9aaeFtt6b3c-P72sDmaDnX68qyokl8Q"
time="2019-08-13T22:50:11Z" level=error msg="Unable to obtain ACME certificate for domains \"nms01.mydomain.com\" detected thanks to rule \"Host:nms01.mydomain.com\" : unable to generate a certificate for the domains [nms01.mydomain.com]: acme: Error -> One or more domains had a problem:\n[nms01.mydomain.com] acme: error: 400 :: urn:ietf:params:acme:error:connection :: Fetching http://nms01.mydomain.com/.well-known/acme-challenge/9TDG1jFz_LqkBQa33d9Rg12k5aLZiUjl0T-on5vb6SA: Timeout during connect (likely firewall problem), url: \n"
time="2019-08-13T22:50:22Z" level=info msg="Skipping same configuration for provider d
```
and

```
time="2019-08-13T22:46:20Z" level=error msg="Unable to obtain ACME certificate for domains \"nms01.mydomain.com\" detected thanks to rule \"Host:nms01.mydomain.com\" : unable to generate a certificate for the domains [nms01.mydomain.com]: acme: Error -> One or more domains had a problem:\n[nms01.mydomain.com] acme: error: 400 :: urn:ietf:params:acme:error:connection :: unknownHost :: No valid IP addresses found for nms01.mydomain.com, url: \n"

```

and 

```
time="2019-08-13T22:36:43Z" level=info msg="legolog: [INFO] Unable to deactivate the authorization: https://acme-v02.api.letsencrypt.org/acme/authz/IbJNFPoMMUIB2PeLgOvBYUaw0hlSKrJB3bLeL3U2Tp8"
time="2019-08-13T22:36:43Z" level=error msg="Unable to obtain ACME certificate for domains \"nms01.mydomain.com\" detected thanks to rule \"Host:nms01.mydomain.com\" : unable to generate a certificate for the domains [nms01.mydomain.com]: acme: Error -> One or more domains had a problem:\n[nms01.mydomain.com] acme: error: 400 :: urn:ietf:params:acme:error:connection :: dns :: DNS problem: NXDOMAIN looking up A for nms01.mydomain.com, url: \n"


```

**Comment by crazy-max** [comment]
@ckozler I think that's outside the scope of this image but we can improve documentation. I think this can be linked to #30 right?

**Comment by ckozler** [comment]
Yes I'd say so @crazy-max. I think there are just some documentation enhancements that could be done by someone running through this one time with the current docs and reporting what isnt completely clear. Since this was my fist run through, I think I could provide some feedback if I could submit a pull request?

**Comment by crazy-max** [comment]
@ckozler Yeah sure feel free to open a PR!
