### ISSUE TITLE
Docker image need to support new scheduler 

### ISSUE THREAD

**Issue by Jellyfrog** [librenms/docker#350]
Basically need to add another cronjob that runs `php artisan schedule:run` every minute 
https://github.com/librenms/librenms/pull/14987

**Comment by hugalafutro** [comment]
I presume this is this validate error? I am getting that since updating the docker images to librenms 23.5.0 - Thu Jun 15 2023 03:54:54 GMT+0100
```
SchedulerFailure
FAIL: Scheduler is not running
Fix:
cp /opt/librenms/dist/librenms-scheduler.service /opt/librenms/dist/librenms-scheduler.timer /etc/systemd/system/
systemctl enable librenms-scheduler.timer
systemctl start librenms-scheduler.timer
```
however I cannot run those commands in the docker as:
```
pi@pi-docker:~ $ docker exec -it librenms bash
librenms:/opt/librenms# cp /opt/librenms/dist/librenms-scheduler.service /opt/librenms/dist/librenms-scheduler.timer /etc/systemd/system/
cp: target '/etc/systemd/system/': No such file or directory
```
So then as workaround I can run this from host's cron every minute?
```
pi@pi-docker:~ $ docker exec -t librenms php artisan schedule:run

   INFO  No scheduled commands are ready to run.
```

**Comment by viptampa** [comment]
I have the same issue.   Whats the recommended solution?

**Comment by hugalafutro** [comment]
I tried the solution I mentioned, but when I checked just now it was FAIL again, so I've no idea. However for what it's worth I do not observe any adverse effects either.

**Comment by viptampa** [comment]
> 

Groovy, I'll try that to get around.

**Comment by viptampa** [comment]
Yea, that "docker exec -t librenms php artisan schedule:run" runs.... but of course needs to be then run setup to run when server boots. 

Scheduler still doesn't validate.

**Comment by viptampa** [comment]
So after some working through several iterations... one has to import the cron file under /opt/libernms/dist into the crontab (for librenms user) AND also the php artisan schedule:run.
I can't seem an easy way to automatic that within the container itself.

**Comment by stanthewizzard** [comment]
same issue here

**Comment by exptom** [comment]
I'm trying to do a new install (I want to move from observium) and have hit this same issue.

**Comment by viptampa** [comment]
I posted a work around here. 
https://community.librenms.org/t/docker-container-install-scheduler-not-running-and-servername/21835/2
All things validate.

**Comment by viptampa** [comment]
@crazy-max   Trying to set this up on a brand new linux box, and the scheduler is still not running / validating.

**Comment by crazy-max** [comment]
> @crazy-max Trying to set this up on a brand new linux box, and the scheduler is still not running / validating.

If you"re looking for logs they are discarding: https://github.com/librenms/docker/blob/a88f2d0b1c2e4bd3d9604fb8f54efbd65bb726cb/rootfs/etc/cont-init.d/07-svc-cron.sh#L34

and cron runs fine on my side

**Comment by viptampa** [comment]
Understood.  Looks like validation works via command line, but does not validate via gui.  Suggestions?
