### ISSUE TITLE
Container start but blocks on  [cont-init.d] 07-svc.cron

### ISSUE THREAD

**Issue by democles9308** [librenms/docker#352]
### Behaviour
Setup is an LXC container in Proxmox-7.4.3 with an  Debian 11 template, updated and  docker installed as per info on docker website. 

#### Steps to reproduce this issue

1.  install docker container via portainer by creating stack (librenms) and copy/paste the compose file and adding the env  vars
2. start the stack : all green & running but  librenms goes down due to KILL SIGNAL

#### Expected behaviour

> containers should all work well and  app should be available with browser for further setup

#### Actual behaviour

>  deploy stack in portainer, 
     DB: ok (ready to accept connections),  
2023-04-29 08:56:38+02:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.5.19+maria~ubu2004 started.
2023-04-29 08:56:39+02:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2023-04-29 08:56:40+02:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.5.19+maria~ubu2004 started.
2023-04-29 08:56:40+02:00 [Note] [Entrypoint]: MariaDB upgrade not required
2023-04-29  8:56:40 0 [Note] Starting MariaDB 10.5.19-MariaDB-1:10.5.19+maria~ubu2004 source revision f8a85af8ca1c937b8d4f847477bd282f80251cde as process 1
2023-04-29  8:56:40 0 [Note] InnoDB: Uses event mutexes
2023-04-29  8:56:40 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2023-04-29  8:56:40 0 [Note] InnoDB: Number of pools: 1
2023-04-29  8:56:40 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
2023-04-29  8:56:40 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
2023-04-29  8:56:40 0 [Note] InnoDB: Using Linux native AIO
2023-04-29  8:56:40 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
2023-04-29  8:56:40 0 [Note] InnoDB: Completed initialization of buffer pool
2023-04-29  8:56:40 0 [Note] InnoDB: 128 rollback segments are active.
2023-04-29  8:56:40 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2023-04-29  8:56:40 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2023-04-29  8:56:40 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2023-04-29  8:56:40 0 [Note] InnoDB: 10.5.19 started; log sequence number 858760; transaction id 1482
2023-04-29  8:56:40 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2023-04-29  8:56:40 0 [Note] Plugin 'FEEDBACK' is disabled.
2023-04-29  8:56:40 0 [Note] Server socket created on IP: '::'.
2023-04-29  8:56:40 0 [Note] InnoDB: Buffer pool(s) load completed at 230429  8:56:40
2023-04-29  8:56:41 0 [Note] Reading of all Master_info entries succeeded
2023-04-29  8:56:41 0 [Note] Added new Master_info '' to hash table
2023-04-29  8:56:41 0 [Note] mysqld: ready for connections.
Version: '10.5.19-MariaDB-1:10.5.19+maria~ubu2004'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution 

     REDIS: OK ready to accept connections

1:C 29 Apr 2023 08:56:38.153 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 29 Apr 2023 08:56:38.153 # Redis version=5.0.14, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 29 Apr 2023 08:56:38.153 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 29 Apr 2023 08:56:38.156 * Running mode=standalone, port=6379.
1:M 29 Apr 2023 08:56:38.156 # Server initialized
1:M 29 Apr 2023 08:56:38.156 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 29 Apr 2023 08:56:38.156 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
1:M 29 Apr 2023 08:56:38.156 * Ready to accept connections

     LIBRENMS: NOK - sending  TERM/KILL Signal

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-fix-logs.sh: executing... 
[cont-init.d] 00-fix-logs.sh: exited 0.
[cont-init.d] 01-fix-uidgid.sh: executing... 
[cont-init.d] 01-fix-uidgid.sh: exited 0.
[cont-init.d] 02-fix-perms.sh: executing... 
Fixing perms...
[cont-init.d] 02-fix-perms.sh: exited 0.
[cont-init.d] 03-config.sh: executing... 
Setting timezone to Europe/Brussels...
Setting PHP-FPM configuration...
Setting PHP INI configuration...
Setting OpCache configuration...
Setting Nginx configuration...
Updating SNMP community...
Initializing LibreNMS files / folders...
Setting LibreNMS configuration...
Checking LibreNMS plugins...
Fixing perms...
Checking additional Monitoring plugins...
Checking alert templates...
[cont-init.d] 03-config.sh: exited 0.
[cont-init.d] 04-svc-main.sh: executing... 
Waiting 60s for database to be ready...
Database ready!
Updating database schema...
Nothing to migrate.
Seeding: Database\Seeders\DefaultAlertTemplateSeeder
Seeded:  Database\Seeders\DefaultAlertTemplateSeeder (1.00ms)
Seeding: Database\Seeders\DefaultLegacySchemaSeeder
Seeded:  Database\Seeders\DefaultLegacySchemaSeeder (0.53ms)
Seeding: Database\Seeders\ConfigSeeder
Seeded:  Database\Seeders\ConfigSeeder (1.48ms)
Database seeding completed successfully.
Clear cache
Application cache cleared!
Configuration cache cleared!
Configuration cached successfully!
[cont-init.d] 04-svc-main.sh: exited 0.
[cont-init.d] 05-svc-dispatcher.sh: executing... 
[cont-init.d] 05-svc-dispatcher.sh: exited 0.
[cont-init.d] 06-svc-syslogng.sh: executing... 
[cont-init.d] 06-svc-syslogng.sh: exited 0.
[cont-init.d] 07-svc-cron.sh: executing... 
mkdir: cannot create directory ‘/var/spool/cron/crontabs’: Invalid argument
[cont-init.d] 07-svc-cron.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

### Configuration

services:
  db:
    image: mariadb:10.5
    container_name: librenms_db
    command:
      - "mysqld"
      - "--innodb-file-per-table=1"
      - "--lower-case-table-names=0"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - "/dockerdata/librenms/db:/var/lib/mysql"
    environment:
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "REDIS_HOST=${REDIS_HOST}"
    restart: always

  redis:
    image: redis:5.0-alpine
    container_name: librenms_redis
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "REDIS_HOST=${REDIS_HOST}"
    restart: always

  librenms:
    image: librenms/librenms:23.2.0
    container_name: librenms
    hostname: librenms
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
    depends_on:
      - db
      - redis
    volumes:
      - "/dockerdata/librenms/data:/data"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
      - "REDIS_HOST=${REDIS_HOST}"
    restart: always

ENVs 
TZ=Europe/Brussels
MYSQL_DATABASE=librenms
MYSQL_USER=librenms
MYSQL_PASSWORD= **SOMESECRETPWD**
MEMORY_LIMIT=256M
MAX_INPUT_VARS=1000
UPLOAD_MAX_SIZE=16M
OPCACHE_MEM_SIZE=128
REAL_IP_FROM=192.168.41.54/32
REAL_IP_HEADER=X-Forwarded-For
LOG_IP_VAR=remote_addr
CACHE_DRIVER=redis
SESSION_DRIVER=redis
REDIS_HOST=redis
LIBRENMS_SNMP_COMMUNITY=on4crm_public
LIBRENMS_WEATHERMAP=false
PUID=997
PGID=997

997 is librenms user/group on the hostsystem

### Docker info
Hostname | docker
Version | 23.0.5 (API: 1.42)
Root directory | /dockerdata
Storage Driver | overlay2
Logging Driver | json-file
Volume Plugins | local
Network Plugins | bridge, host, ipvlan, macvlan, null, overlay

OS Information | linux x86_64 Debian GNU/Linux 11 (bullseye)
Kernel Version | 5.15.104-1-pve
Total CPU | 2
Total memory | 2.1 GB

> Output of command `docker info`
root@docker:/dockerdata/containers# docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.17.3)
  scan: Docker Scan (Docker Inc., v0.23.0)

Server:
 Containers: 3
  Running: 2    >>>> edit : DB and REDIS
  Paused: 0
  Stopped: 1  >>>> edit : LIBRENMS
 Images: 5
 Server Version: 23.0.5
 Storage Driver: overlay2
  Backing Filesystem: zfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: false
  userxattr: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: v1.1.5-0-gf19387a
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.104-1-pve
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 2GiB
 Name: docker
 ID: OKK7:RLVD:6SVE:3AOH:QNUD:BCCQ:W5KQ:BBHM:S2US:FAUW:MK3Q:G43R
 Docker Root Dir: /dockerdata
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: API is accessible on http://192.168.41.54:2375 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/go/attack-surface/
### Logs
see above

**Comment by crazy-max** [comment]
What's the output of dmesg? This does not seems an issue with the image but your host environment.

What gives you the following commands?:

```
$ docker run -it alpine
/ # ls -al /var/spool
/ # rm -rf /var/spool/cron
```

**Comment by democles9308** [comment]
@crazy-max , thanks for your support !  could create a working stack on another server... it must gave been a host problem. I'll try to resreate te stack on my proxmox server en will comment. However I'll close the ticket for the time being.

**Comment by yannik995** [comment]
Hi, I had the same problem, seems to affect containers that are unprivileged and also with nesting and keyctl.
https://pve.proxmox.com/wiki/Linux_Container#pct_options

With a privileged LXC container in which Apparmor has been removed (apt remove apparmor && reboot) and nesting activated it works.
