### ISSUE TITLE
Case Insensitive Table Names do not pass validation

### ISSUE THREAD

**Issue by jasonTriplett1** [librenms/docker#356]
When installing on Docker for Deskop on Windows, the lower case table names flag for mariadb must be set to 1, or mariadb will not start.

However, the database validation fails. It seems that the validator is not recognizing the case insensitive table names.

https://mariadb.com/kb/en/server-system-variables/#lower_case_table_names

**Comment by crazy-max** [comment]
Would need repro with logs
