### ISSUE TITLE
container images not updated.

### ISSUE THREAD

**Issue by glance-** [librenms/docker#358]
#### Steps to reproduce this issue

```
# date
Thu May 25 11:51:58 AM CEST 2023

# docker pull librenms/librenms
Using default tag: latest
latest: Pulling from librenms/librenms
Digest: sha256:a71f4a4763d40bf008d97bed82a1c956b4fb6a636ae96d582f3cae23f59cc349
Status: Image is up to date for librenms/librenms:latest
docker.io/librenms/librenms:latest

# docker inspect -f '{{ printf "%s\n" .Created }}{{ index .Config.Labels "org.opencontainers.image.version" }}' librenms/librenms:latest 
2023-03-24T11:46:35.492020389Z
23.2.0
```

#### Expected behaviour

I'd expect the container image to contain the released 23.5.0 version of librenms

#### Actual behaviour

The librenms/librenms:latest is still at 23.2.0

**Comment by ryanmerolle** [comment]
It probably just makes sense to setup the workflow to auto build and publish the images at this point sort of like what we do in [netbox-docker](https://github.com/netbox-community/netbox-docker)
