### ISSUE TITLE
Anonymous volume created by rrdcached

### ISSUE THREAD

**Issue by BeresfordHare** [librenms/docker#37]
### Behaviour
Anonymous volume is created by rrdcached container.

#### Steps to reproduce this issue
Using the librenms docker-compose.yml file.

1. docker-compose up -d
2. docker volume ls
3. anonymous volume has been created by rrdcached
4. docker-compose down
5. remove anonymous volume
6. remove rrdcached from docker-compose.yml
7. docker-compose up -d 
8. docker volume ls
9. no anonymous volumes are created.

#### Expected behaviour

No anonymous volumes should be created.

#### Actual behaviour

Anonymous volume is created by rrdcached container.

### Configuration

* Docker version (type `docker --version`) : Docker version 19.03.2, build 6a30dfc
* Docker compose version if applicable (type `docker-compose --version`) : docker-compose version 1.24.1, build 4667896b
* Platform (Debian 9, Ubuntu 18.04, ...) : Debian 10

### Docker info

```
Client:
 Debug Mode: false

Server:
 Containers: 7
  Running: 6
  Paused: 0
  Stopped: 1
 Images: 7
 Server Version: 19.03.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-5-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 3.832GiB
 Name: 
 ID: ESKN:QCAL:Y224:7N3F:5V6R:77UY:IPGK:WBBQ:34GE:NV5T:M7LZ:VBE5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by crazy-max** [comment]
Hi @xpatux, can you create a proper [bug report](https://github.com/librenms/docker/issues/new?template=bug_report.md) please?

**Comment by crazy-max** [comment]
Pull the latest rrdcached image, this should be fixed.
