### ISSUE TITLE
usermod takes too long

### ISSUE THREAD

**Issue by xpatux** [librenms/docker#38]
Hi,

We have been running librenms on docker for about a year. 

Now we're having a problem when try to start a new instance of Web UI.

Every time a container with this image starts, there is a usermod command to change the UID of librenms user so it can match rrd files owner on the filesystem. It takes for ever. We have about 200G of rrd data for about 3k devices. We can't set healthcheck correctly because it has to wait too much.

How can this be fixed?

https://github.com/librenms/docker/blob/d627abc4067f0fc90277c54d500244c60bfb816a/entrypoint.sh#L78

**Comment by crazy-max** [comment]
Hi @xpatux, can you create a proper [bug report](https://github.com/librenms/docker/issues/new?template=bug_report.md) please?

**Comment by crazy-max** [comment]
@xpatux Pull the latest image, this sohuld be fixed.

**Comment by xpatux** [comment]
Thanks @crazy-max.

Finally, I changed the PUID and PGID variables and rrd files owner to default 1000, because a few things popps up after the image pull, like sidecar cron container stopped alerting. It wasn't capable to acquire lock on alerts.

We are now working with default PUID/PGID and short start time on every container.
