### ISSUE TITLE
Update Redis to Supported Version

### ISSUE THREAD

**Issue by jdsatava127** [librenms/docker#426]
The example docker compose.yml at https://github.com/librenms/docker/blob/57ae77c697630de26b37efbbb0a5de28b7a50cef/examples/compose/compose.yml#L24 lists 5.0-alpine as the version for Redis. According to https://docs.redis.com/latest/rs/installing-upgrading/product-lifecycle/ that version has been end of life for a few years now. Can we get this updated to a newer supported version?

**Comment by vk6xebec** [comment]
I've upgraded my compose file to 'redis:7.2.4-alpine' and I haven't found any issues. I also upgraded to mariadb 10.11 without issues. However, upgrading to Mariadb 11.3.2 breaks LibreNMS with the following error:

```
2024-03-27 16:26:30+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:11.3.2+maria~ubu2204 started.
2024-03-27 16:26:30+00:00 [ERROR] [Entrypoint]: mariadbd failed while attempting to check config
        command was: mysqld --innodb-file-per-table=1 --lower-case-table-names=0 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --verbose --help
        /usr/local/bin/docker-entrypoint.sh: line 105: mysqld: command not found
```

**Comment by roock** [comment]
redis was update to version 7.2 in https://github.com/librenms/docker/commit/3131ae9f5bfe325a1159f6d28b22429d3db870f0

Issue can be closed @crazy-max
