### ISSUE TITLE
Device Perf schema change on April 10th

### ISSUE THREAD

**Issue by choward420** [librenms/docker#432]
### Description

Any chance we could get a new build with the latest schema change?  If you drop your paypal, I'll give 100$ :D

Long story, but my main instance (not dockerized) is running daily.php as of recent...  The schema changed borked 20 out of 40 of my pollers and it's broken my alerting.  Not sure if you have CI/CD going, but if you could cut an EDGE release from the most recent schema, I'd be grateful.

**Comment by choward420** [comment]
FYI, my main instance current build info:

===========================================
Component | Version
--------- | -------
LibreNMS  | 24.3.0-23-g49f8269 (2024-04-18T09:57:01-05:00)
DB Schema | 2024_04_10_093513_remove_device_perf (291)
PHP       | 8.1.14
Python    | 3.6.8
Database  | MariaDB 10.5.21-MariaDB
RRDTool   | 1.7.1
SNMP      | 5.7.2

**Comment by murrant** [comment]
All your instances need to be running the same version. Running mismatched versions is not supported.
