### ISSUE TITLE
MEMCACHED_PORT default port not working

### ISSUE THREAD

**Issue by tik-stbuehler** [librenms/docker#48]
`MEMCACHED_PORT` is used for `LIBRENMS_DISTRIBUTED_POLLER_MEMCACHED_PORT` before the default is applied (https://github.com/librenms/docker/blob/master/rootfs/etc/cont-init.d/03-config.sh#L37-L44).

**Comment by crazy-max** [comment]
@tik-stbuehler Good catch, thanks!

**Comment by crazy-max** [comment]
@tik-stbuehler Should be fixed now
