### ISSUE TITLE
Multiple discovery threads ?

### ISSUE THREAD

**Issue by kedare** [librenms/docker#59]
Hello.

I think it would be interesting to support multiple discovery threads (as it's currently hardcoded to 1 in the crontab file) like the multiple pollers thread.

I see data randomly disapearing from the devices (like the IPs), I think it's because the whole discovery process take too long with a single thread. (running manually the discovery on just the ipv4 and ipv6 modules make them appear back typically)

Also I think it could be interesting to have an easy way to add custom lines in the cron file

Thanks.

**Comment by crazy-max** [comment]
@kedare I think this is more likely a general LibreNMS feature. Any thoughts on that @murrant @laf?

**Comment by kedare** [comment]
LibreNMS does support it, it's just that in the Docker image, the parameter for discovery is not configurable.

**Comment by crazy-max** [comment]
@kedare Should be ok now through `LIBRENMS_CRON_DISCOVERY_WRAPPER_WORKERS` en var.

**Comment by kedare** [comment]
Great, thanks, I will try next week :)

**Comment by murrant** [comment]
I wonder if we should be using the python dispatch service in the docker
