### ISSUE TITLE
exited with code 1

### ISSUE THREAD

**Issue by PenChien** [librenms/docker#62]
#### Steps to reproduce this issue

1. # docker-composer up -d

#### Expected behaviour

excute # docker-composer up -d

no error messages.

#### Actual behaviour

excute # docker-composer up -d
logs show exited with coded as below

librenms exited with code 1
librenms_cron exited with code 1
librenms_syslog exited with code 1

### Configuration

* Docker version (type `docker --version`) :Docker version 1.13.1, build b2f74b2/1.13.1

* Docker compose version if applicable (type `docker-compose --version`) : docker-compose version 1.25.4, build 8d51620a

* Platform (Debian 9, Ubuntu 18.04, ...) : CentOS 7

* System info (type `uname -a`) : Linux docker01.m1.am 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

### Docker info

```
> Output of command `docker info`
Containers: 7
 Running: 4
 Paused: 0
 Stopped: 3
Images: 9
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 9c3c5f853ebf0ffac0d087e94daef462133b69c7 (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
 selinux
Kernel Version: 3.10.0-957.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 1
Total Memory: 1.795 GiB
Name: docker01.m1.am
ID: LSQ5:U6AM:4UWT:SAW2:5EAG:3X4L:5C2W:MD3Y:A24X:UOO6:C477:NCHW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: docker.io (secure)


### Logs

```
> Container logs (set LOG_LEVEL to debug if applicable)
```
cron_1       | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
cron_1       | [s6-init] ensuring user provided files have correct perms...exited 0.
cron_1       | [fix-attrs.d] applying ownership & permissions fixes...
cron_1       | [fix-attrs.d] done.
cron_1       | [cont-init.d] executing container initialization scripts...
cron_1       | [cont-init.d] 00-fix-logs.sh: executing...
cron_1       | [cont-init.d] 00-fix-logs.sh: exited 0.
cron_1       | [cont-init.d] 01-fix-uidgid.sh: executing...
cron_1       | [cont-init.d] 01-fix-uidgid.sh: exited 0.
cron_1       | [cont-init.d] 02-fix-perms.sh: executing...
cron_1       | Fixing perms...
cron_1       | chown: cannot access '/var/run/nginx': No such file or directory
cron_1       | chown: cannot access '/var/run/php-fpm': No such file or directory
cron_1       | [cont-init.d] 02-fix-perms.sh: exited 1.
cron_1       | [cont-finish.d] executing container finish scripts...
cron_1       | [cont-finish.d] done.
cron_1       | [s6-finish] waiting for services.
cron_1       | [s6-finish] sending all processes the TERM signal.
cron_1       | [s6-finish] sending all processes the KILL signal and exiting.
librenms     | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
librenms     | [s6-init] ensuring user provided files have correct perms...exited 0.
librenms     | [fix-attrs.d] applying ownership & permissions fixes...
librenms     | [fix-attrs.d] done.
librenms     | [cont-init.d] executing container initialization scripts...
librenms     | [cont-init.d] 00-fix-logs.sh: executing...
librenms     | [cont-init.d] 00-fix-logs.sh: exited 0.
librenms     | [cont-init.d] 01-fix-uidgid.sh: executing...
librenms     | [cont-init.d] 01-fix-uidgid.sh: exited 0.
librenms     | [cont-init.d] 02-fix-perms.sh: executing...
librenms     | Fixing perms...
librenms     | [cont-init.d] 02-fix-perms.sh: exited 1.
librenms     | chown: cannot access '/var/run/nginx': No such file or directory
librenms     | chown: cannot access '/var/run/php-fpm': No such file or directory
librenms     | [cont-finish.d] executing container finish scripts...
librenms     | [cont-finish.d] done.
librenms     | [s6-finish] waiting for services.
librenms     | [s6-finish] sending all processes the TERM signal.
librenms     | [s6-finish] sending all processes the KILL signal and exiting.
rrdcached_1  | Creating configuration...
rrdcached_1  | Fixing perms...
rrdcached_1  | starting up
rrdcached_1  | checking for journal files
rrdcached_1  | replaying from journal: /data/journal/rrd.journal.1584355556.102128
rrdcached_1  | Replayed 0 entries (0 failures)
rrdcached_1  | replaying from journal: /data/journal/rrd.journal.1584355721.072680
rrdcached_1  | Replayed 0 entries (0 failures)
rrdcached_1  | journal processing complete
rrdcached_1  | listening for connections
smtp_1       | Setting configuration option myhostname with value: librenms.example.com
smtp_1       | Setting configuration option mydomain with value: example.com
smtp_1       | Setting configuration option mydestination with value: $myhostname
smtp_1       | Setting configuration option myorigin with value: $mydomain
smtp_1       | Setting configuration option relayhost with value: [smtp.example.com]:587
smtp_1       | Setting configuration option smtp_use_tls with value: yes
smtp_1       | Setting configuration option smtp_sasl_auth_enable with value: yes
smtp_1       | Setting configuration option smtp_sasl_password_maps with value: hash:/etc/postfix/sasl_passwd
smtp_1       | Setting configuration option smtp_sasl_security_options with value: noanonymous
smtp_1       | Adding SASL authentication configuration
smtp_1       | Setting configuration option mynetworks with value: 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16
smtp_1       | /usr/lib/python2.7/site-packages/supervisor/options.py:296: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
smtp_1       |   'Supervisord is running as root and it is searching '
smtp_1       | 2020-03-16 07:00:21,953 CRIT Supervisor running as root (no user in config file)
smtp_1       | 2020-03-16 07:00:21,953 WARN Included extra file "/etc/supervisord.d/postfix.ini" during parsing
smtp_1       | 2020-03-16 07:00:21,953 WARN Included extra file "/etc/supervisord.d/readlog.ini" during parsing
smtp_1       | 2020-03-16 07:00:21,953 WARN Included extra file "/etc/supervisord.d/rsyslog.ini" during parsing
smtp_1       | 2020-03-16 07:00:21,975 INFO RPC interface 'supervisor' initialized
smtp_1       | 2020-03-16 07:00:21,975 CRIT Server 'unix_http_server' running without any HTTP authentication checking
smtp_1       | 2020-03-16 07:00:21,975 INFO supervisord started with pid 1
smtp_1       | 2020-03-16 07:00:22,977 INFO spawned: 'master' with pid 25
smtp_1       | 2020-03-16 07:00:22,983 INFO spawned: 'readlog' with pid 26
smtp_1       | 2020-03-16 07:00:22,985 INFO spawned: 'rsyslog' with pid 27
smtp_1       | 2020-03-16 07:00:23,405 INFO success: master entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
smtp_1       | 2020-03-16 07:00:23,405 INFO exited: master (exit status 0; expected)
smtp_1       | 2020-03-16 07:00:24,406 INFO success: readlog entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
smtp_1       | 2020-03-16 07:00:24,406 INFO success: rsyslog entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
librenms_syslog | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
librenms_syslog | [s6-init] ensuring user provided files have correct perms...exited 0.
librenms_syslog | [fix-attrs.d] applying ownership & permissions fixes...
librenms_syslog | [fix-attrs.d] done.
librenms_syslog | [cont-init.d] executing container initialization scripts...
librenms_syslog | [cont-init.d] 00-fix-logs.sh: executing...
librenms_syslog | [cont-init.d] 00-fix-logs.sh: exited 0.
librenms_syslog | [cont-init.d] 01-fix-uidgid.sh: executing...
librenms_syslog | [cont-init.d] 01-fix-uidgid.sh: exited 0.
librenms_syslog | [cont-init.d] 02-fix-perms.sh: executing...
librenms_syslog | Fixing perms...
librenms_syslog | chown: cannot access '/var/run/nginx': No such file or directory
librenms_syslog | chown: cannot access '/var/run/php-fpm': No such file or directory
librenms_syslog | [cont-init.d] 02-fix-perms.sh: exited 1.
librenms_syslog | [cont-finish.d] executing container finish scripts...
librenms_syslog | [cont-finish.d] done.
librenms_syslog | [s6-finish] waiting for services.
librenms_syslog | [s6-finish] sending all processes the TERM signal.
librenms_syslog | [s6-finish] sending all processes the KILL signal and exiting.

#  docker logs librenms
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-fix-logs.sh: executing...
[cont-init.d] 00-fix-logs.sh: exited 0.
[cont-init.d] 01-fix-uidgid.sh: executing...
[cont-init.d] 01-fix-uidgid.sh: exited 0.
[cont-init.d] 02-fix-perms.sh: executing...
Fixing perms...
[cont-init.d] 02-fix-perms.sh: exited 1.
chown: cannot access '/var/run/nginx': No such file or directory
chown: cannot access '/var/run/php-fpm': No such file or directory
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by crazy-max** [comment]
@PenChien

> Include all necessary configuration files : docker-compose.yml, .env, ...

Please include those files without sensitive values.

**Comment by PenChien** [comment]
as below, thanks.

# docker-compose.yml
version: "3.5"

services:
  db:
    image: mariadb:10.2
    container_name: librenms_db
    command:
      - "mysqld"
      - "--sql-mode="
      - "--innodb-file-per-table=1"
      - "--lower-case-table-names=0"
      - "--character-set-server=utf8"
      - "--collation-server=utf8_unicode_ci"
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      - "TZ=${TZ}"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    restart: always

  memcached:
    image: memcached:alpine
    container_name: librenms_memcached
    environment:
      - "TZ=${TZ}"
    restart: always

  rrdcached:
    image: crazymax/rrdcached
    container_name: librenms_rrdcached
    volumes:
      - "./librenms/rrd:/data/db"
      - "./rrd-journal:/data/journal"
    environment:
      - "TZ=${TZ}"
      - "LOG_LEVEL=LOG_INFO"
      - "WRITE_TIMEOUT=1800"
      - "WRITE_JITTER=1800"
      - "WRITE_THREADS=4"
      - "FLUSH_DEAD_DATA_INTERVAL=3600"
    restart: always

  smtp:
    image: juanluisbaptiste/postfix
    container_name: librenms_smtp
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - "SERVER_HOSTNAME=librenms.example.com"
      - "SMTP_SERVER=${SMTP_SERVER}"
      - "SMTP_USERNAME=${SMTP_USERNAME}"
      - "SMTP_PASSWORD=${SMTP_PASSWORD}"
    restart: always

  librenms:
    image: librenms/librenms:latest
    container_name: librenms
    domainname: example.com
    hostname: librenms
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
    depends_on:
      - db
      - memcached
      - rrdcached
      - smtp
    volumes:
      - "./librenms:/data"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
    env_file:
      - "./librenms.env"
    restart: always

  cron:
    image: librenms/librenms:latest
    container_name: librenms_cron
    domainname: example.com
    hostname: librenms
    depends_on:
      - librenms
    volumes:
      - "./librenms:/data"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
      - "SIDECAR_CRON=1"
    env_file:
      - "./librenms.env"
    restart: always

  syslog-ng:
    image: librenms/librenms:latest
    container_name: librenms_syslog
    domainname: example.com
    hostname: librenms
    depends_on:
      - librenms
    ports:
      - target: 514
        published: 514
        protocol: tcp
      - target: 514
        published: 514
        protocol: udp
    volumes:
      - "./librenms:/data"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
      - "SIDECAR_SYSLOGNG=1"
    env_file:
      - "./librenms.env"
    restart: always

#.env
MYSQL_DATABASE=librenms
MYSQL_USER=librenms
MYSQL_PASSWORD=asupersecretpassword

SMTP_SERVER=smtp.example.com
SMTP_USERNAME=smtp@example.com
SMTP_PASSWORD=

TZ=Europe/Paris
PUID=1000
PGID=1000



#librenms.env
MEMORY_LIMIT=256M
UPLOAD_MAX_SIZE=16M
OPCACHE_MEM_SIZE=128
REAL_IP_FROM=0.0.0.0/32
REAL_IP_HEADER=X-Forwarded-For
LOG_IP_VAR=remote_addr

LIBRENMS_POLLER_THREADS=16
LIBRENMS_POLLER_INTERVAL=5

LIBRENMS_CRON_DISCOVERY_ENABLE=true
LIBRENMS_CRON_DAILY_ENABLE=true
LIBRENMS_CRON_ALERTS_ENABLE=true
LIBRENMS_CRON_BILLING_ENABLE=true
LIBRENMS_CRON_BILLING_CALCULATE_ENABLE=true
LIBRENMS_CRON_CHECK_SERVICES_ENABLE=true
LIBRENMS_CRON_POLLER_ENABLE=true
LIBRENMS_CRON_SNMPSCAN_ENABLE=true
LIBRENMS_CRON_SNMPSCAN_NETS=192.168.0.0/24,192.168.1.0/24
LIBRENMS_CRON_SNMPSCAN_LOGFILE=/data/logs/snmp-scan.log

LIBRENMS_SNMP_COMMUNITY=librenmsdocker
MEMCACHED_HOST=memcached
MEMCACHED_PORT=11211
RRDCACHED_HOST=rrdcached
RRDCACHED_PORT=42217

**Comment by crazy-max** [comment]
@PenChien Do you have SELinux enabled on your host?

**Comment by PenChien** [comment]
I have disabled SELinux, and still the same issue.

**Comment by crazy-max** [comment]
@PenChien Can you run the following command and give me the output please?: `docker run --rm -t --entrypoint "/bin/ls" librenms/librenms:latest -al /var/run`

**Comment by PenChien** [comment]
[root@docker01 ~]# docker run --rm -t --entrypoint "/bin/ls" librenms/librenms:latest -al /var/run
lrwxrwxrwx 1 root root 4 Jan 23 14:36 /var/run -> /run

**Comment by crazy-max** [comment]
Missing slash sorry, try this now: `docker run --rm -t --entrypoint "/bin/ls" librenms/librenms:latest -al /run/`

**Comment by chrisdessert** [comment]
I'm having the same issue, here is my output of the above command.

[root@librenms docker]# docker run --rm -t --entrypoint "/bin/ls" librenms/librenms:latest -al /run/
total 0
drwxr-xr-x 1 root root 21 Mar 25 19:35 .
drwxr-xr-x 1 root root 17 Mar 25 19:35 ..
drwxr-xr-x 2 root root  6 Mar 22 15:54 nginx
drwxr-xr-x 2 root root  6 Mar 22 15:54 php-fpm
drwxr-xr-x 2 root root  6 Mar 25 19:35 secrets

**Comment by PenChien** [comment]
[root@docker01 ~]#   docker run --rm -t --entrypoint "/bin/ls" librenms/librenms:latest -al /run/
total 0
drwxr-xr-x 1 root root 21 Mar 26 02:41 .
drwxr-xr-x 1 root root 17 Mar 26 02:41 ..
drwxr-xr-x 2 root root  6 Mar 22 15:54 nginx
drwxr-xr-x 2 root root  6 Mar 22 15:54 php-fpm
drwxr-xr-x 2 root root  6 Mar 26 02:41 secrets

**Comment by crazy-max** [comment]
Will take a look, keep you in touch. Btw @chrisdessert, CentOS too?

**Comment by chrisdessert** [comment]
Yes, CentOS 7.

**Comment by 357up** [comment]
I am facing the same issue on Centos 8. 
As a dirty  workaround I edited `rootfs/etc/cont-init.d/02-fix-perms.sh` and replaced the last line with following:
`( chown -R librenms: /tpls /var/lib/nginx /var/log/nginx /var/log/php7 /var/run/nginx /var/run/php-fpm ) || true`. Then I rebuilt the image.
This way altough the command  fails, the container does not terminate. I was then able to get shell, create` /var/run/nginx` and `/var/run/php-fpm` directories manually and change owner to librenms user. nginx and php-fpm processes started automatically and everything seems to work. I hope this is somewhat helpfull.

**Comment by crazy-max** [comment]
Should be fixed now
