### ISSUE TITLE
Docker image can't start on non ipv6 host

### ISSUE THREAD

**Issue by FlyveHest** [librenms/docker#71]
### Behaviour
When starting a default install of librenms, nginx can't start if the host have disabled IPv6

#### Steps to reproduce this issue

1. Run librenms docker image

#### Expected behaviour

LibreNMS starts

#### Actual behaviour

nginx can't bind to ipv6 socket, and doesn't start.

### Logs

Apr 28 22:47:44 docker/librenms[1728]: 2020/04/28 22:47:44 [emerg] 628#628: socket() [::]:8000 failed (97: Address family not supported by protocol)                                                                                      
Apr 28 22:47:44 - docker/librenms[1728]: nginx: [emerg] socket() [::]:8000 failed (97: Address family not supported by protocol)                      

### Proposed fix
Add a toggle to disable ipv6 for nginx, maybe just be specifying the listening socket in a variable. (Making that configurable would also be quite nice)

Copying the nginx.conf from /tpls/etc/nginx/nginx.conf, editing it and copying it back "resolves" the issue.

**Comment by crazy-max** [comment]
@FlyveHest Yes we could use `ipv6only` nginx directive here:

```
        listen 8000;
        listen [::]:8000 ipv6only=on;
```

Can you test this?

**Comment by FlyveHest** [comment]
Yes, setting ipv6only to on (or off) still makes nginx try and listen on an ipv6 socket.

As far as I can read from the docs, the setting determines if an ipv6 socket will listen on both ipv4 and 6, or ipv6 only, not that it will listen if ipv6 is available.

I think the only fix is to make the ipv6 listen parameter an ENV variable that can be overwritten with an empty string, making it not try to listen at all.

**Comment by murrant** [comment]
ipv6only=on is already the default.

Pretty silly but seems like the only fix is to add a IPV4_ONLY flag.

**Comment by FlyveHest** [comment]
Alternately, maybe add a LISTEN and LISTEN_IPV6 environment variable, and if not set, just don't add / remove the relevant listen line.

I added a init-cont.d script of my own to the image that comments the ipv6 listen line (and also disables access logging as I already have that from the reverse proxy I run in front of the container)

**Comment by crazy-max** [comment]
@FlyveHest I will make some changes around this. Keep you in touch.

**Comment by crazy-max** [comment]
@FlyveHest [`LISTEN_IPV6`](https://github.com/librenms/docker/blob/master/doc/docker/environment-variables.md#general) env var has been added.
