### ISSUE TITLE
CORS on nginx

### ISSUE THREAD

**Issue by iffanux** [librenms/docker#73]
Hello,
Im having an issue with nginx cors, even thought I've edit nginx.conf then restart the docker but it didn't change the conf. It always revert to original conf.

===============Error Respond==============
Access to XMLHttpRequest at "https://mydomain"  has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by crazy-max** [comment]
@iffanux Please create a proper [bug report](https://github.com/librenms/docker/issues/new?template=bug_report.md).
