### ISSUE TITLE
Not working correctly with fresh install

### ISSUE THREAD

**Issue by seanbranam** [librenms/docker#75]
Followed the instructions on a new Ubuntu 18 server, graphs not creating rrdcache logs show failed requests.

Created a /var/librenms dir and dropped in 3 files and edited appropriately.

First I noticed that after docker-compse up -d , the config.php file that is in the librenms docker is not the same as the one in github.
The bottom 2 lines are not preset in config.php.default and I was unable to create my own config.php file on the /data/config folder.

So far that's the only thing I changed.

I do see something strange though, docker compose created a db dir with permissions that are not the same as the other dirs it created.
db  is set to 999:root
Not sure if that is an issue.

Would be great to see a step by step how to, in case I did something wrong.

**Comment by crazy-max** [comment]
@seanbranam Please create a proper [bug report](https://github.com/librenms/docker/issues/new?template=bug_report.md).
