### ISSUE TITLE
Error with new device added - no graphs

### ISSUE THREAD

**Issue by seanbranam** [librenms/docker#76]
### Behavior
Graphs not being created

#### Steps to reproduce this issue

1. Add device via http://hostname:8000/addhost
2.
3.

#### Expected behavior

Graphs created

#### Actual behavior

The device directory is created as root:root , in /var/librenms/librenms/rrd/(device dir)

### Configuration

* Docker version (type `docker --version`) : 19.03.8
* Docker compose version if applicable (type `docker-compose --version`) : 4.1.0
* Platform (Debian 9, Ubuntu 18.04, ...) : Ubuntu 18.04
* System info (type `uname -a`) : 4.15.0.99-generic #100-Ubuntu SMP x86_64
* Include all necessary configuration files : 
[env_file.txt](https://github.com/librenms/docker/files/4618036/env_file.txt)

[docker-compose_yml.txt](https://github.com/librenms/docker/files/4618038/docker-compose_yml.txt)

[librenms_env.txt](https://github.com/librenms/docker/files/4618042/librenms_env.txt)

### Docker info

[docker_info.txt](https://github.com/librenms/docker/files/4618061/docker_info.txt)

### Logs

![docker_log](https://user-images.githubusercontent.com/5049550/81738199-2f4a9b80-944e-11ea-9145-c29e3563c23d.png)

**Comment by crazy-max** [comment]
@seanbranam As stipulated, in [Volumes doc](https://github.com/librenms/docker/blob/master/doc/docker/volumes.md#volumes), the volume should be owned by the user/group with the specified `PUID` and `PGID`. In your case: `chown -R 1000:1000 ./data`. And [same thing](https://github.com/crazy-max/docker-rrdcached#volumes) for rrdcached container.

**Comment by asteen-nexcess** [comment]
@crazy-max I'm seeing the same issue here too. I've chowned the directories before starting to 1000:1000, but every time I add a new host, the new host rrd directory is added with root:root. Requires me to chown the directories again after every host add.

**Comment by crazy-max** [comment]
@asteen-nexcess Okay, thanks for the clarification, I'll take a closer look.

**Comment by seanbranam** [comment]
@crazy-max Thanks for the reply. 
The volumes doc were owned by the same user with the PUID and PGID. I'm seeing the same as @asteen-nexcess.
To note, the first device I added, I chown the dir so graphs would work. Then as a test I added a second device and that was again created with root:root permission, and errors were shown by the rrdcached docker, unable to write the .rrd files.

**Comment by apollo13** [comment]
I am seeing the same, whoever is generating the host folder seems to be running as root user. Especially
```
root         327     324  0 12:18 ?        00:00:15 python3 /opt/librenms/librenms-service.py -v
```
shines out, though I have no idea who is indeed creating those directories.

**Comment by crazy-max** [comment]
@seanbranam @asteen-nexcess @apollo13 I have made changes. Can you pull the latest and tell me if it works now?

**Comment by apollo13** [comment]
@crazy-max Jupp, that fixed it for me. Many thanks for the quick fix!

**Comment by seanbranam** [comment]
@crazy-max Yes that worked . thank you!
