### ISSUE TITLE
Persistent new models / OS configurations

### ISSUE THREAD

**Issue by MattCrumPCN** [librenms/docker#77]
Hi - I've been playing around with the Bluecat Networks OS configuration per this thread:

https://community.librenms.org/t/oxidized-vendor-model-type/12025/13

It's now returning some fields that my organization will find useful (model name vs a generic "bluecat" result); but I don't know how to make the change persist through Docker container updates. The data volume that I'm using for librenms is mapped to /etc/librenms/librenms on the host and it contains a few persistent folders:

```
drwxr-xr-x. 2 librenms librenms  65 May 12 17:24 config
drwxrwxr-x. 2 librenms librenms  26 May 10 16:36 logs
drwxr-xr-x. 2 librenms librenms 109 May 11 16:40 monitoring-plugins
drwxrwxr-x. 9 librenms librenms 154 May 14 12:00 rrd
drwxr-xr-x. 2 librenms librenms   6 May 10 16:36 syslog-ng
```
Is there a way to add a "models" or similar folder to here, which will store my custom configurations?

Thanks,
Matt

**Comment by crazy-max** [comment]
Hi @MattCrumPCN, the base folder for librenms in this image is `/opt/librenms` so you can bind mount your file with something like this `./myfile.php:/opt/librenms/path/to/myfile.php`
