### ISSUE TITLE
compose file hostname and domainname

### ISSUE THREAD

**Issue by ozmend** [librenms/docker#8]
in .env file there are hostname end domainname variables.
i expected that it takes them for app "traefik.frontend.rule=" 

but, it takes baremetal host's hostname and domainname.
I tried to run it in my local docker and atomic. 
because of the name issue it returns 404 not found.
I solved it by changing "traefik.frontend.rule=${HOSTNAME}.${DOMAINNAME}" into "traefik.frontend.rule=mynms.example.com" and defined it in my dns

**Comment by ozmend** [comment]
Hi,

yes, all files are under same folder.
other apps gets ${HOSTNAME} and ${DOMAINNAME} as what i write in env file.But "librenms_app" takes main host's names. 
For example i use centos 7 and my machine name is ozmend.example.com.
I wrote hostname=nms, domainname=example.com into env file.
It took ozmend.example.com.
because of matcher doest work right web page returns "404 not found"
if i set "traefik.frontend.rule" manually as nms.example.com it works fine.
I found the problem after i opened traefik statistic web page (port=8080)

Maybe it is syntax problem. I used your compose file with traefik latest image and toml file.
Same result

**Comment by crazy-max** [comment]
Ok thanks for your input, I will investigate on this

**Comment by crazy-max** [comment]
Based on moby/moby#20200 we should avoid these env vars. Related to #6 too.

**Comment by ozmend** [comment]
Docker version 1.13.1, build 07f3374/1.13.1
Kernel Version: 3.10.0-957.1.3.el7.x86_64
Operating System: CentOS Linux 7.1811 (Core)
OSType: linux
Architecture: x86_64

docker-compose version 1.23.2, build 1110ad01
