### ISSUE TITLE
No Webserver if Sidecar-Container enabled

### ISSUE THREAD

**Issue by as149** [librenms/docker#83]
Hi,
the script `docker/rootfs/etc/cont-init.d/04-svc-main.sh` will exit, if a Sidecar-Container ist enabled.

So no nginx or php or other Services will be startet.

What is to be done to use Librenms-WebGUI with Sidecar-Containers?

Stizi

**Comment by crazy-max** [comment]
@as149 Sidecar containers are not intended to run Nginx. You have to use another container for that. Take a look at the list of containers required in the [compose example](https://github.com/librenms/docker/blob/master/examples/compose/docker-compose.yml). More info [here](https://github.com/librenms/docker/blob/master/doc/usage.md).
