### ISSUE TITLE
Using traefik composer example results in smtp dependency error.

### ISSUE THREAD

**Issue by AOGCrewdawg** [librenms/docker#87]
Line 101 of docker/examples/traefik/docker-compose.yml should read msmtpd instead of SMTP

#### Steps to reproduce this issue

1. download docker/examples/traefik/
2. docker-compose up -d
3.

#### Expected behaviour

Successful launch of containers

#### Actual behaviour

ERROR: Service 'librenms' depends on service 'smtp' which is undefined.

### Configuration

* Docker version (type `docker --version`) : Docker version 19.03.6-ce, build 369ce74
* Docker compose version if applicable (type `docker-compose --version`) :  
docker-compose version 1.26.0, build d4451659
* Platform (Debian 9, Ubuntu 18.04, ...) : AWS Linux AMI
* System info (type `uname -a`) : Linux ip-172-30-0-41 4.14.181-108.257.amzn1.x86_64 #1 SMP Wed May 27 02:43:03 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

### Docker info

```
Server:
 Containers: 9
  Running: 9
  Paused: 0
  Stopped: 0
 Images: 7
 Server Version: 19.03.6-ce
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ff48f57fc83a8c44cf4ad5d672424a98ba37ded6
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.14.181-108.257.amzn1.x86_64
 Operating System: Amazon Linux AMI 2018.03
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.853GiB
 Name: ip-172-30-0-41
 ID: G22F:EGCC:2D66:VI4H:PEZ7:BXZ3:KGGT:LE77:QUL7:K26C:Y5AB:6D6P
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

### Logs

```
> Container logs (set LOG_LEVEL to debug if applicable)
```

**Comment by crazy-max** [comment]
@AOGCrewdawg Fixed thanks!
