### ISSUE TITLE
WeatherMap permissions

### ISSUE THREAD

**Issue by DonovanEsterhuizen** [librenms/docker#90]
Hi

How can i resolve the permissions issue below

librenms      | PHP Warning:  imagepng(weathermap.png): failed to open stream: Permission denied in /opt/librenms/html/plugins/Weathermap/lib/Weathermap.class.php on line 3321
librenms      | WARNING: configs//another.conf: Failed to create image file weathermap.png - permissions of output directory are wrong? [WMWARN14]
librenms      | PHP Deprecated:  The each() function is deprecated. This message will be suppressed on further calls in /opt/librenms/html/plugins/Weathermap/lib/Weathermap.class.php on line 778
librenms      | PHP Warning:  imagepng(weathermap.png): failed to open stream: Permission denied in /opt/librenms/html/plugins/Weathermap/lib/Weathermap.class.php on line 3321
librenms      | WARNING: configs//weathermap: Failed to create image file weathermap.png - permissions of output directory are wrong? [WMWARN14]
librenms      | PHP Deprecated:  The each() function is deprecated. This message will be suppressed on further calls in /opt/librenms/html/plugins/Weathermap/lib/Weathermap.class.php on line 778
librenms      | WARNING: configs//Test.conf: ReadData: LINK switch-firewall, target: ./192.168.2.1/port-id1.rrd:INOCTETS:OUTOCTETS on config line 60 of configs//Test.conf had no valid data, according to WeatherMapDataSource_rrd
librenms      | WARNING: configs//Test.conf: ReadData: LINK firewall-node08317, target: ./192.168.2.21/port-id132.rrd:INOCTETS:OUTOCTETS on config line 66 of configs//Test.conf had no valid data, according to WeatherMapDataSource_rrd

Thanks

**Comment by crazy-max** [comment]
@DonovanEsterhuizen Please create a proper [bug report](https://github.com/librenms/docker/issues/new?template=bug_report.md).
