### ISSUE TITLE
Custom Script

### ISSUE THREAD

**Issue by HalianElf** [librenms/docker#92]
Is it possible to have the container run a custom script on startup? I'm trying to run a nagios plugin and I need some extra packages for it to work. If not a custom script, some way to have it install extra packages.

**Comment by crazy-max** [comment]
@HalianElf,

> Is it possible to have the container run a custom script on startup?

This is not good practice when writing Docker images.

> If not a custom script, some way to have it install extra packages.

But you can create your own Docker image based on this one:

```
FROM librenms/librenms:latest

...
```
