### ISSUE TITLE
Dispatcher cluster not working, Same NODE_ID

### ISSUE THREAD

**Issue by mskorge** [librenms/docker#93]
### Behaviour

Not sure if this is a common issue, or just a configuration error on my side... 
The new dispatcher service seems to work fine when using a single container. When adding an additional to act like a cluster it seems to be processing something, but never shows up in the poller view. Looking into it I noticed they both have the same NODE_ID in the .env file which is also used to populate the dispatchers in the DB. The documentation states NODE_ID needs to be unique for every dispatcher node.

Is NODE_ID supposed to be generated for each container, or is it pre-added when building the container image?

#### Steps to reproduce this issue

1. Add a dispatcher container
2. Add an additional container serving the same group
3. Look at the poller part of the GUI or dispatcher table in database

#### Expected behaviour

The second node should be displayed as an additional node in the same dispatcher cluster

#### Actual behaviour

It seems to be acting as a duplicate of the first dispatcher node

### Configuration

* Platform: Ubuntu/Kubernetes

**Comment by crazy-max** [comment]
Duplicated of #3

**Comment by mskorge** [comment]
Hi @crazy-max and thanks for all your work!

I think I wasn't clear on what the problem was here. It really has nothing to do with k8s/swarm, just poller-clusters in librenms.
I did some more testing to be more specific:

For the dispatcher service to work properly NODE_ID in /opt/librenms/.env needs to be unique and APP_ID needs to be the same. Since NODE_ID is set by composer when building the docker image it will always be the same when using the same image version.

I verified this by building my own image from this repo to generate a new NODE_ID. Using that image to add an additional dispatcher service container worked fine and it shows up in the web-gui under /pollers:
![image](https://user-images.githubusercontent.com/2026554/86324787-6021a280-bc3f-11ea-938d-79dd7e97635a.png)

Not sure if NODE_ID should always be unique for every librenms container, or if just applies to dispatchers/pollers, but I guess we need some logic to handle this, either by setting a environment variable or automated in your init scripts. I guess you don't want it to change when updating the image or restarting the container so if it can be saved on persistent volumes that would probably be preferred.

Let me know if I can assist in any way.

**Comment by crazy-max** [comment]
@mskorge,

> For the dispatcher service to work properly NODE_ID in /opt/librenms/.env needs to be unique and APP_ID needs to be the same. Since NODE_ID is set by composer when building the docker image it will always be the same when using the same image version.

You're right, I will fix that. This will be apply this behavior only to the dispatcher.

**Comment by murrant** [comment]
@crazy-max is the APP_KEY hardcoded too? APP_KEY should be unique per install, but the same for all nodes in a cluster.

**Comment by crazy-max** [comment]
@murrant Yes indeed I was thinking of this too. I will manage the persistence of this data for future updates.

**Comment by crazy-max** [comment]
The `librenms/librenms:edge` should fix your issue:

![image](https://user-images.githubusercontent.com/1951866/86487526-dd3b3d80-bd4d-11ea-802f-2e0aab9c4fb0.png)

The env var [`LIBRENMS_SERVICE_NODE_ID`](https://github.com/librenms/docker/blob/master/doc/docker/environment-variables.md#dispatcher-service) has been introduced to define a node ID for your dispatcher(s).

**Comment by crazy-max** [comment]
Should be fixed through 1.65. See [CHANGELOG](https://github.com/librenms/docker/blob/master/CHANGELOG.md#165-rc1-20200703) for more info.
