### ISSUE TITLE
Can't Create Poller Group

### ISSUE THREAD

**Issue by BraydenBrekke** [librenms/docker#95]
### Behaviour

Adding a poller group within the GUI produces no response
#### Steps to reproduce this issue

1. Fill out Poller Group form with a group name and description
2. Click Add Poller Group

#### Expected behaviour

The form closes, and a group is added

#### Actual behaviour

The Form does not respond to submitting "Add Poller Group"

### Configuration

* Docker version (type `docker --version`) : Docker version 19.03.12, build 48a66213fe
* Docker compose version if applicable (type `docker-compose --version`) : docker-compose version 1.26.0, build d4451659
* Platform (Debian 9, Ubuntu 18.04, ...) : Ubuntu 18.04

### Docker info

```
Client:
 Debug Mode: false

Server:
 Containers: 10
  Running: 9
  Paused: 0
  Stopped: 1
 Images: 12
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.3.0-1023-aws
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.786GiB
 Name: ip-172-29-1-31
 ID: Y47K:AGGF:FY4Y:NDHE:MB5S:ML7I:TDRE:ABIV:YBKR:M432:KXLB:LSLK
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

### Logs
Librenms Container Log does not show any request when I submit the form.

**Comment by crazy-max** [comment]
@BraydenBrekke, I don't think this is related to the Docker image itself but LibreNMS. Did you hear about that, @murrant ?

**Comment by crazy-max** [comment]
@BraydenBrekke After investigating with @murrant, this issue is linked to the "Specific URL" (`base_url`) setting. Go to `https://librenms.example.com/settings/system/server` and fill in the proper info.

**Comment by rigocalin** [comment]
Thanks. For me it solved this issues and others like not being able to delete devices....etc.

**Comment by BraydenBrekke** [comment]
Yep, That worked for me too. Thanks!

**Comment by crazy-max** [comment]
@rigocalin @BraydenBrekke Latest image (1.65.1) should solve the `base_url` issue through the [`LIBRENMS_BASE_URL` env var](https://github.com/librenms/docker/blob/master/doc/docker/environment-variables.md#misc) (default to `/`).
