### ISSUE TITLE
No environment Variable to Define Poller Name

### ISSUE THREAD

**Issue by BraydenBrekke** [librenms/docker#96]
### Behaviour
Each Poller is Named Librenms. 
#### Expected behaviour
An environment variable to define librenms' distributed_poller_name configuration
#### Actual behaviour
Environment variable is not defined, so each poller has name librenms
![Screenshot from 2020-07-06 11-06-52](https://user-images.githubusercontent.com/51920996/86615247-d133c380-bf79-11ea-8c5b-d6d22ede8aec.png)

**Comment by crazy-max** [comment]
@BraydenBrekke The name of the poller is the [hostname of your container](https://github.com/librenms/docker/blob/4be8d30631a7721a58e6a7527775f395321de8ff/examples/compose/docker-compose.yml#L92).

**Comment by murrant** [comment]
It does seem odd you can't override that in the webui though... upstream issue.
