### ISSUE TITLE
Fresh install can't capture debug information

### ISSUE THREAD

**Issue by blakeaa827** [librenms/docker#98]
Hello,

I started having polling issues on my current install.  So I created a fresh environment for troubleshooting, and I'm seeing similar behavior under this fresh installation.  I cloned the git project and copied the files from the example directory for compose.  I updated the environment variables as appropriate, and brought everything up with compose.  I am able to log into the new instance using the default librenms user.  I am also able to successfully add a device, which indicates to me SNMP is working.  However when I try to capture the SNMP communication using the debug utility from the web ui, nothing works.  Chrome/Edge just give a blank grey box without any information.  Firefox at least provides the following when I click "Run":

```
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

This worked without any issues a couple of weeks ago.  I also checked the librenms log file, and identified that it's not being updated with any messages when I click "run" from the debug utility.

Thanks, and please let me know if I can provide additional information.

**Comment by mzac** [comment]
Interesting I have the same issue.  Running in k3s with the dispatcher service.

**Comment by crazy-max** [comment]
@blakeaa827 Have you applied the [Upgrade notes](https://github.com/librenms/docker/blob/master/CHANGELOG.md#165-rc1-20200703)?

**Comment by mzac** [comment]
I updated the base_url and that fixed the discovery portion, but as per the other issue #97 my rrd files are still not getting updated.

**Comment by blakeaa827** [comment]
> @blakeaa827 Have you applied the [Upgrade notes](https://github.com/librenms/docker/blob/master/CHANGELOG.md#165-rc1-20200703)?

Thanks for the suggestion.  I have updated that with the ip address of the server and restarted the containers.  The debug page is still giving the same result, 404.

**Comment by crazy-max** [comment]
@blakeaa827 

>  The debug page is still giving the same result, 404.

I'm not aware of that kind of page. What is the base url of it? Also if you need further help, please create a proper [bug report](https://github.com/librenms/docker/issues/new?template=bug_report.md).

**Comment by mzac** [comment]
http://librenms.lab.local/device/4/capture is the page for example

**Comment by murrant** [comment]
capture is not for manually running discovery/polling.  It is for troubleshooting.  It will not update RRDs.

**Comment by crazy-max** [comment]
@mzac @blakeaa827 Latest image (1.65.1) should solve the `base_url` issue through the [`LIBRENMS_BASE_URL` env var](https://github.com/librenms/docker/blob/master/doc/docker/environment-variables.md#misc) (default to `/`).

**Comment by mzac** [comment]
Thanks I'll check it out later tonight!
